/* eslint-disable @typescript-eslint/no-explicit-any */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/empty-state";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { can } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { archiveIndicatorCatalog, createIndicatorCatalog, createIndicatorVersion, requestCalculation, updateIndicatorVersionStatus } from "@/modules/analytics/actions";
import { indicatorTemplates } from "@/modules/analytics/schemas";

const pageSize = 20;
const value = (data: any) => data ?? "Sin dato";

export default async function AnalyticsPage({ params, searchParams }: { params: Promise<{ organizationId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { organizationId } = await params; const query = await searchParams;
  const text = typeof query.q === "string" ? query.q : ""; const periodStart = typeof query.period_start === "string" ? query.period_start : ""; const periodEnd = typeof query.period_end === "string" ? query.period_end : ""; const legalEntityId = typeof query.legal_entity_id === "string" ? query.legal_entity_id : ""; const siteId = typeof query.site_id === "string" ? query.site_id : "";
  const { supabase } = await requireAuthenticatedUser(); const db = supabase as any;
  const [read, manage, approve] = await Promise.all([can(organizationId, "analytics.read"), can(organizationId, "analytics.manage"), can(organizationId, "analytics.approve")]);
  if (!read) return <EmptyState title="Sin permiso" description="Solicita acceso a indicadores y analítica." />;
  let resultQuery = db.from("indicator_results").select("*, indicator_versions(formula_description, periodicity, source_config, version_number, indicator_catalog(id, name, code))", { count: "exact" }).eq("organization_id", organizationId).order("period_end", { ascending: false }).range(0, pageSize - 1);
  if (periodStart) resultQuery = resultQuery.gte("period_start", periodStart); if (periodEnd) resultQuery = resultQuery.lte("period_end", periodEnd); if (legalEntityId) resultQuery = resultQuery.eq("legal_entity_id", legalEntityId); if (siteId) resultQuery = resultQuery.eq("site_id", siteId);
  const [catalog, versions, results, live, legalEntities, sites, members] = await Promise.all([
    db.from("indicator_catalog").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(pageSize),
    db.from("indicator_versions").select("*").eq("organization_id", organizationId).order("indicator_id").order("version_number", { ascending: false }).limit(100),
    resultQuery,
    db.from("management_dashboard_metrics").select("*").eq("organization_id", organizationId).maybeSingle(),
    db.from("legal_entities").select("id,legal_name").eq("organization_id", organizationId).eq("status", "active").order("legal_name"),
    db.from("sites").select("id,name,legal_entity_id").eq("organization_id", organizationId).eq("status", "active").order("name"),
    db.from("organization_members").select("user_id").eq("organization_id", organizationId).eq("status", "active"),
  ]);
  const memberIds = (members.data ?? []).map((member:any) => member.user_id);
  const { data: memberProfiles } = memberIds.length ? await db.from("profiles").select("id,first_name,last_name").in("id", memberIds) : { data: [] };
  const memberNames = new Map<string, string>((memberProfiles ?? []).map((profile:any) => [String(profile.id), [profile.first_name, profile.last_name].filter(Boolean).join(" ") || "Persona sin nombre"]));
  const hidden = <input type="hidden" name="organizationId" value={organizationId} />;
  const filteredScope = Boolean(legalEntityId || siteId);
  return <main className="grid gap-6 p-6"><header><h1 className="text-3xl font-semibold">Indicadores y analítica</h1><p className="mt-1 text-sm text-[var(--muted)]">Los resultados históricos son snapshots calculados en servidor. El estado vivo nunca reemplaza el histórico.</p></header>
    <form className="grid gap-2 rounded-xl border bg-[var(--surface)] p-4 md:grid-cols-6"><Input name="q" placeholder="Buscar indicador" defaultValue={text}/><Input name="period_start" type="date" defaultValue={periodStart}/><Input name="period_end" type="date" defaultValue={periodEnd}/><select name="legal_entity_id" defaultValue={legalEntityId}><option value="">Todas las razones sociales</option>{legalEntities.data?.map((item:any)=><option key={item.id} value={item.id}>{item.legal_name}</option>)}</select><select name="site_id" defaultValue={siteId}><option value="">Todas las sedes</option>{sites.data?.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><Button type="submit">Filtrar</Button></form>
    <section><h2 className="mb-3 text-xl font-semibold">Estado vivo actual</h2>{filteredScope ? <EmptyState title="Sin desglose disponible" description="Las tres métricas iniciales se calculan a nivel de organización. El filtro se aplicará a resultados futuros que cuenten con ese alcance."/> : <div className="grid gap-3 md:grid-cols-3"><Card><CardHeader><CardTitle>Tareas abiertas</CardTitle></CardHeader><CardContent className="text-3xl font-semibold">{value(live.data?.open_tasks)}</CardContent></Card><Card><CardHeader><CardTitle>Acciones abiertas</CardTitle></CardHeader><CardContent className="text-3xl font-semibold">{value(live.data?.open_actions)}</CardContent></Card><Card><CardHeader><CardTitle>Documentos activos</CardTitle></CardHeader><CardContent className="text-3xl font-semibold">{value(live.data?.active_documents)}</CardContent></Card></div>}</section>
    {manage ? <section className="grid gap-3 lg:grid-cols-2"><Card><CardHeader><CardTitle>Nuevo indicador</CardTitle></CardHeader><CardContent><form action={createIndicatorCatalog} className="grid gap-2">{hidden}<Input name="code" placeholder="TAREAS_ABIERTAS" required/><Input name="name" placeholder="Nombre" required/><Textarea name="description" placeholder="Propósito y contexto"/><select name="owner_user_id"><option value="">Sin responsable</option>{members.data?.map((member:any)=><option key={member.user_id} value={member.user_id}>{memberNames.get(member.user_id) ?? "Persona sin nombre"}</option>)}</select><Button>Crear catálogo</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Nueva versión</CardTitle></CardHeader><CardContent><form action={createIndicatorVersion} className="grid gap-2">{hidden}<select name="indicator_id" required><option value="">Selecciona un indicador</option>{catalog.data?.filter((item:any)=>item.status === "active").map((item:any)=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><Input name="version_number" type="number" min="1" defaultValue="1" required/><select name="template">{Object.entries(indicatorTemplates).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><Textarea name="formula_description" placeholder="Descripción funcional y explicable de la fórmula" required/><select name="periodicity"><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="monthly" defaultValue="monthly">Mensual</option><option value="quarterly">Trimestral</option><option value="yearly">Anual</option></select><Input name="target_value" type="number" step="0.01" placeholder="Meta opcional"/><select name="target_direction"><option value="at_least">Al menos</option><option value="at_most">Como máximo</option><option value="exact">Exactamente</option></select><Input name="effective_from" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Input name="effective_to" type="date"/><Button>Guardar borrador</Button></form></CardContent></Card></section> : null}
    <section className="grid gap-3"><h2 className="text-xl font-semibold">Catálogo y versiones</h2>{catalog.data?.length ? catalog.data.filter((item:any)=>!text || `${item.code} ${item.name}`.toLowerCase().includes(text.toLowerCase())).map((item:any)=><Card key={item.id}><CardHeader><CardTitle>{item.code} · {item.name} <span className="ml-2 text-sm font-normal text-[var(--muted)]">{item.status}</span></CardTitle></CardHeader><CardContent className="grid gap-3">{item.description?<p className="text-sm text-[var(--muted)]">{item.description}</p>:null}{versions.data?.filter((version:any)=>version.indicator_id===item.id).map((version:any)=><div key={version.id} className="rounded-lg border p-3 text-sm"><p><b>v{version.version_number}</b> · {version.status} · {version.periodicity}</p><p>Fórmula: {version.formula_description}</p><p>Fuente: {indicatorTemplates[version.source_config?.template as keyof typeof indicatorTemplates] ?? "No soportada"} · Meta: {version.target_value ?? "Sin meta"} ({version.target_direction})</p><div className="mt-2 flex flex-wrap gap-2">{version.status === "draft" && approve ? <form action={updateIndicatorVersionStatus}>{hidden}<input type="hidden" name="id" value={version.id}/><input type="hidden" name="status" value="approved"/><Button size="sm">Aprobar versión</Button></form>:null}{version.status === "approved" && manage ? <form action={requestCalculation} className="flex flex-wrap gap-2">{hidden}<input type="hidden" name="indicator_version_id" value={version.id}/><Input name="period_start" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Input name="period_end" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Button size="sm">Calcular snapshot</Button></form>:null}</div></div>)}{manage && item.status === "active" ? <form action={archiveIndicatorCatalog}>{hidden}<input type="hidden" name="id" value={item.id}/><Button size="sm" variant="secondary">Archivar indicador</Button></form>:null}</CardContent></Card>) : <EmptyState title="Sin indicadores" description="Crea un indicador y después una versión en borrador."/>}</section>
    <section className="grid gap-3"><h2 className="text-xl font-semibold">Resultados históricos</h2>{results.data?.length ? results.data.map((result:any)=><Card key={result.id}><CardContent><div className="flex flex-wrap justify-between gap-2"><b>{result.indicator_versions?.indicator_catalog?.code} · {result.indicator_versions?.indicator_catalog?.name}</b><span>{result.period_start} a {result.period_end}</span></div><p className="mt-2 text-2xl font-semibold">{result.value}</p><p className="text-sm text-[var(--muted)]">v{result.indicator_versions?.version_number} · meta {result.target_value ?? "sin meta"} · {result.target_direction_snapshot}</p><p className="text-sm text-[var(--muted)]">{result.formula_snapshot}</p><p className="text-xs text-[var(--muted)]">{result.explanation?.kind === "current_state_snapshot" ? "Corte de estado actual" : "Resultado histórico"} · calculado {result.explanation?.measured_at ?? result.created_at}</p></CardContent></Card>) : <EmptyState title="Sin resultados para el filtro" description="Aprueba una versión y solicita un cálculo autorizado. Los resultados no se editan ni reemplazan."/>}</section>
  </main>;
}
