"use client";

import * as DropdownMenuPrimitive from "@radix-ui/react-dropdown-menu";
import { Check, CaretRight, Circle } from "@phosphor-icons/react";
import type { ComponentProps } from "react";
import { cn } from "@/lib/utils";

export const DropdownMenu = DropdownMenuPrimitive.Root;
export const DropdownMenuTrigger = DropdownMenuPrimitive.Trigger;
export const DropdownMenuGroup = DropdownMenuPrimitive.Group;
export const DropdownMenuRadioGroup = DropdownMenuPrimitive.RadioGroup;
export const DropdownMenuSub = DropdownMenuPrimitive.Sub;
export function DropdownMenuContent({ className, sideOffset = 7, ...props }: ComponentProps<typeof DropdownMenuPrimitive.Content>) { return <DropdownMenuPrimitive.Portal><DropdownMenuPrimitive.Content sideOffset={sideOffset} className={cn("z-50 min-w-52 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-1.5 text-sm shadow-[var(--shadow-overlay)] outline-none data-[state=open]:animate-[popover-in_140ms_ease-out]", className)} {...props} /></DropdownMenuPrimitive.Portal>; }
export function DropdownMenuItem({ className, inset, ...props }: ComponentProps<typeof DropdownMenuPrimitive.Item> & { inset?: boolean }) { return <DropdownMenuPrimitive.Item className={cn("relative flex min-h-9 cursor-default select-none items-center gap-2 rounded-lg px-2.5 py-2 outline-none transition-colors focus:bg-[var(--muted-surface)] focus:text-[var(--foreground)] data-[disabled]:pointer-events-none data-[disabled]:opacity-45", inset && "pl-8", className)} {...props} />; }
export function DropdownMenuLabel({ className, inset, ...props }: ComponentProps<typeof DropdownMenuPrimitive.Label> & { inset?: boolean }) { return <DropdownMenuPrimitive.Label className={cn("px-2.5 py-2 text-xs font-semibold text-[var(--muted)]", inset && "pl-8", className)} {...props} />; }
export function DropdownMenuSeparator({ className, ...props }: ComponentProps<typeof DropdownMenuPrimitive.Separator>) { return <DropdownMenuPrimitive.Separator className={cn("-mx-1 my-1 h-px bg-[var(--border)]", className)} {...props} />; }
export function DropdownMenuCheckboxItem({ className, children, checked, ...props }: ComponentProps<typeof DropdownMenuPrimitive.CheckboxItem>) { return <DropdownMenuPrimitive.CheckboxItem checked={checked} className={cn("relative flex min-h-9 cursor-default select-none items-center rounded-lg py-2 pl-8 pr-2.5 outline-none focus:bg-[var(--muted-surface)] data-[disabled]:pointer-events-none data-[disabled]:opacity-45", className)} {...props}><span className="absolute left-2.5 grid size-4 place-items-center"><DropdownMenuPrimitive.ItemIndicator><Check size={14} weight="bold" /></DropdownMenuPrimitive.ItemIndicator></span>{children}</DropdownMenuPrimitive.CheckboxItem>; }
export function DropdownMenuRadioItem({ className, children, ...props }: ComponentProps<typeof DropdownMenuPrimitive.RadioItem>) { return <DropdownMenuPrimitive.RadioItem className={cn("relative flex min-h-9 cursor-default select-none items-center rounded-lg py-2 pl-8 pr-2.5 outline-none focus:bg-[var(--muted-surface)] data-[disabled]:pointer-events-none data-[disabled]:opacity-45", className)} {...props}><span className="absolute left-2.5 grid size-4 place-items-center"><DropdownMenuPrimitive.ItemIndicator><Circle size={8} weight="fill" /></DropdownMenuPrimitive.ItemIndicator></span>{children}</DropdownMenuPrimitive.RadioItem>; }
export const DropdownMenuSubTrigger = ({ className, children, inset, ...props }: ComponentProps<typeof DropdownMenuPrimitive.SubTrigger> & { inset?: boolean }) => <DropdownMenuPrimitive.SubTrigger className={cn("flex min-h-9 cursor-default select-none items-center rounded-lg px-2.5 py-2 outline-none focus:bg-[var(--muted-surface)] data-[state=open]:bg-[var(--muted-surface)]", inset && "pl-8", className)} {...props}>{children}<CaretRight className="ml-auto" size={14} /></DropdownMenuPrimitive.SubTrigger>;
export function DropdownMenuSubContent({ className, ...props }: ComponentProps<typeof DropdownMenuPrimitive.SubContent>) { return <DropdownMenuPrimitive.SubContent className={cn("z-50 min-w-44 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-1.5 text-sm shadow-[var(--shadow-overlay)] outline-none", className)} {...props} />; }
export function DropdownMenuShortcut({ className, ...props }: ComponentProps<"span">) { return <span className={cn("ml-auto text-xs tracking-widest text-[var(--muted)]", className)} {...props} />; }
