import Link from "next/link";
import { ArrowLeft, Bell, FileText, MoonStars } from "@phosphor-icons/react/dist/ssr";
import { EmptyState } from "@/components/empty-state";
import { FormDrawer } from "@/components/form-drawer";
import { PageHeader } from "@/components/page-header";
import { StatusBanner } from "@/components/status-banner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { can } from "@/modules/auth/permissions";
import { createNotificationTemplate, saveNotificationPreferences, updateNotificationTemplateStatus } from "@/modules/notifications/actions";
import { requireAuthenticatedUser, requireTenant } from "@/modules/organizations/tenant";

export default async function NotificationSettingsPage({ params, searchParams }: { params: Promise<{ organizationId: string }>; searchParams: Promise<{ status?: string }> }) {
  const { organizationId } = await params;
  const { userId, supabase } = await requireAuthenticatedUser();
  await requireTenant(organizationId);
  const [{ data: preferences }, { data: templates }, manage, approve] = await Promise.all([
    supabase.from("notification_preferences").select("in_app_enabled,email_enabled,quiet_hours_start,quiet_hours_end,timezone").eq("organization_id", organizationId).eq("user_id", userId).maybeSingle(),
    supabase.from("notification_templates").select("id,event_type,channel,version_number,title_template,body_template,status,approved_at").eq("organization_id", organizationId).order("event_type").order("version_number", { ascending: false }).limit(100),
    can(organizationId, "notifications.manage"),
    can(organizationId, "notifications.templates_approve"),
  ]);
  const { status } = await searchParams;
  const templateForm = <form action={createNotificationTemplate} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId} /><label className="grid gap-2 text-sm font-medium">Evento<Input name="event_type" placeholder="Ejemplo: task.overdue" required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Canal<Select name="channel"><option value="in_app">Bandeja</option><option value="email">Correo</option></Select></label><label className="grid gap-2 text-sm font-medium">Versión<Input name="version_number" type="number" min="1" defaultValue="1" required /></label></div><label className="grid gap-2 text-sm font-medium">Título<Input name="title_template" placeholder="Título breve y accionable" maxLength={160} required /></label><label className="grid gap-2 text-sm font-medium">Mensaje<Textarea name="body_template" placeholder="Mensaje operativo sin información sensible" maxLength={500} required /></label><p className="text-xs leading-5 text-[var(--muted)]">Las plantillas no aceptan contenido libre del evento. La versión aprobada quedará inmutable.</p><Button type="submit"><FileText size={18} />Guardar borrador</Button></form>;

  return <div className="space-y-6">
    <PageHeader eyebrow="Preferencias personales" title="Configura cómo recibes avisos" description="La bandeja funciona de inmediato. Las horas silenciosas solo aplazan el correo cuando exista un proveedor conectado." action={<Link href={`/org/${organizationId}/notifications`} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-sm font-semibold shadow-[var(--shadow-control)]"><ArrowLeft size={16} />Volver a la bandeja</Link>} />
    <StatusBanner status={status} />
    <Card><CardHeader><CardTitle>Mis preferencias</CardTitle><CardDescription>Estas opciones solo cambian tus avisos dentro de la organización actual.</CardDescription></CardHeader><CardContent><form action={saveNotificationPreferences} className="grid gap-5 md:max-w-2xl"><input type="hidden" name="organizationId" value={organizationId} /><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center justify-between gap-4 rounded-xl border border-[var(--border)] bg-[var(--muted-surface)] p-4"><span><span className="block font-semibold">Bandeja en Securia360</span><span className="mt-1 block text-sm text-[var(--muted)]">Recibe avisos dentro de tu espacio de trabajo.</span></span><Switch name="in_app_enabled" defaultChecked={preferences?.in_app_enabled ?? true} /></label><label className="flex items-center justify-between gap-4 rounded-xl border border-[var(--border)] bg-[var(--muted-surface)] p-4"><span><span className="block font-semibold">Correo</span><span className="mt-1 block text-sm text-[var(--muted)]">Quedará preparado hasta conectar un proveedor.</span></span><Switch name="email_enabled" defaultChecked={preferences?.email_enabled ?? false} /></label></div><div className="grid gap-4 sm:grid-cols-3"><label className="grid gap-2 text-sm font-medium">Zona horaria<Select name="timezone" defaultValue={preferences?.timezone ?? "America/Bogota"}><option value="America/Bogota">Bogotá (UTC−5)</option><option value="UTC">UTC</option></Select></label><label className="grid gap-2 text-sm font-medium">Silencio desde<Input name="quiet_hours_start" type="time" defaultValue={preferences?.quiet_hours_start?.slice(0, 5) ?? ""} /></label><label className="grid gap-2 text-sm font-medium">Silencio hasta<Input name="quiet_hours_end" type="time" defaultValue={preferences?.quiet_hours_end?.slice(0, 5) ?? ""} /></label></div><div className="flex items-start gap-3 rounded-lg border border-[var(--border)] px-4 py-3 text-sm text-[var(--muted)]"><MoonStars size={18} className="mt-0.5 shrink-0" /><p>Las horas silenciosas pueden cruzar medianoche. Los avisos dentro de la aplicación seguirán llegando para que no pierdas trazabilidad.</p></div><Button type="submit" className="w-fit"><Bell size={18} />Guardar preferencias</Button></form></CardContent></Card>
    {manage ? <Card><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle>Plantillas operativas</CardTitle><CardDescription>Mensajes breves, versionados y sin información sensible.</CardDescription></div><FormDrawer title="Nueva plantilla" description="Crea una versión en borrador. Una persona autorizada deberá aprobarla antes de usarla." triggerLabel="Crear plantilla">{templateForm}</FormDrawer></CardHeader><CardContent><div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{templates?.map((template) => <article key={template.id} className="py-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{template.title_template}</p><StatusBadge>{template.status}</StatusBadge></div><p className="mt-1 text-sm text-[var(--muted)]">{template.event_type} · versión {template.version_number} · {template.channel === "in_app" ? "Bandeja" : "Correo"}</p></div>{template.status === "draft" ? <div className="flex gap-2">{approve ? <form action={updateNotificationTemplateStatus}><input type="hidden" name="organizationId" value={organizationId} /><input type="hidden" name="id" value={template.id} /><input type="hidden" name="status" value="approved" /><Button type="submit" size="sm">Aprobar</Button></form> : null}<form action={updateNotificationTemplateStatus}><input type="hidden" name="organizationId" value={organizationId} /><input type="hidden" name="id" value={template.id} /><input type="hidden" name="status" value="archived" /><Button type="submit" size="sm" variant="secondary">Archivar</Button></form></div> : null}</div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">{template.body_template}</p></article>)}{!templates?.length ? <div className="py-6"><EmptyState title="No hay plantillas" description="Mientras no exista una versión aprobada, los eventos compatibles usarán un mensaje genérico y seguro." /></div> : null}</div></CardContent></Card> : null}
  </div>;
}
