"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { can, type PermissionCode } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { communicationSchema, incidentActionSchema, incidentActionStateSchema, incidentCauseSchema, incidentPersonSchema, incidentSchema, incidentStateSchema, investigationSchema, investigationStateSchema } from "./schemas";

const id = z.uuid(); const path=(o:string,s:string)=>`/org/${o}/incidents?status=${s}`;
const org=(f:FormData)=>id.parse(f.get("organizationId")); const values=(f:FormData)=>Object.fromEntries(f);
async function client(){return (await requireAuthenticatedUser()).supabase as any;} async function guard(o:string,p:PermissionCode){if(!(await can(o,p)))redirect(path(o,"forbidden"));}
async function finish(o:string,status:string){revalidatePath(`/org/${o}/incidents`);redirect(path(o,status));}

export async function reportIncident(f:FormData){const o=org(f),x=incidentSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {userId}=await requireAuthenticatedUser();const {error}=await (await client()).from("incidents").insert({organization_id:o,...x.data,reported_by:userId});await finish(o,error?"error":"reported");}
export async function addIncidentPerson(f:FormData){const o=org(f),x=incidentPersonSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {error}=await (await client()).from("incident_people").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function startInvestigation(f:FormData){const o=org(f),x=investigationSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {userId}=await requireAuthenticatedUser();const db=await client();const {error}=await db.from("incident_investigations").insert({organization_id:o,incident_id:x.data.incident_id,methodology_note:x.data.methodology_note,lead_user_id:userId});if(!error)await db.from("incidents").update({status:"under_investigation"}).eq("organization_id",o).eq("id",x.data.incident_id);await finish(o,error?"error":"saved");}
export async function addIncidentCause(f:FormData){const o=org(f),x=incidentCauseSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {error}=await (await client()).from("incident_causes").insert({organization_id:o,incident_investigation_id:x.data.investigation_id,cause_type:x.data.cause_type,description:x.data.description});await finish(o,error?"error":"saved");}
export async function addIncidentAction(f:FormData){const o=org(f),x=incidentActionSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const db=await client();const {error}=await db.from("incident_actions").insert({organization_id:o,...x.data});if(!error)await db.from("incidents").update({status:"actions_open"}).eq("organization_id",o).eq("id",x.data.incident_id);await finish(o,error?"error":"saved");}
export async function updateIncidentState(f:FormData){const o=org(f),x=incidentStateSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,x.data.status==="closed"?"incidents.close":"incidents.manage");const {error}=await (await client()).from("incidents").update({status:x.data.status}).eq("organization_id",o).eq("id",x.data.id);await finish(o,error?"transition-error":"saved");}
export async function updateInvestigationState(f:FormData){const o=org(f),x=investigationStateSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,x.data.status==="closed"?"incidents.close":"incidents.manage");const {error}=await (await client()).from("incident_investigations").update({status:x.data.status, ...(x.data.status==="closed"?{completed_at:new Date().toISOString()}: {})}).eq("organization_id",o).eq("id",x.data.id);await finish(o,error?"transition-error":"saved");}
export async function updateIncidentActionState(f:FormData){const o=org(f),x=incidentActionStateSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,x.data.status==="verified"?"incidents.close":"incidents.manage");const {error}=await (await client()).from("incident_actions").update({status:x.data.status}).eq("organization_id",o).eq("id",x.data.id);await finish(o,error?"transition-error":"saved");}
export async function addIncidentCommunication(f:FormData){const o=org(f),x=communicationSchema.safeParse(values(f));if(!x.success)redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {error}=await (await client()).from("incident_communications").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function uploadIncidentEvidence(f:FormData){const o=org(f),incidentId=id.safeParse(f.get("incident_id")),file=f.get("file");if(!incidentId.success||!(file instanceof File)||file.size<1||file.size>26214400||!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type))redirect(path(o,"invalid"));await guard(o,"incidents.manage");const {userId}=await requireAuthenticatedUser();const db=await client();const documentId=crypto.randomUUID(),versionId=crypto.randomUUID(),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-180)||"evidencia",storagePath=`${o}/incident_evidence/${incidentId.data}/${documentId}/${safe}`;const uploaded=await db.storage.from("evidences").upload(storagePath,file,{contentType:file.type,upsert:false});if(uploaded.error)redirect(path(o,"evidence-error"));const doc=await db.from("documents").insert({id:documentId,organization_id:o,entity_type:"incident_evidence",entity_id:incidentId.data,title:`Incidente · ${file.name}`,created_by:userId,updated_by:userId});const ver=doc.error?{error:doc.error}:await db.from("document_versions").insert({id:versionId,organization_id:o,document_id:documentId,version_number:1,bucket_id:"evidences",storage_path:storagePath,original_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:userId});const link=ver.error?{error:ver.error}:await db.from("incident_evidences").insert({organization_id:o,incident_id:incidentId.data,document_version_id:versionId,visibility:"sensitive"});if(link.error){await db.storage.from("evidences").remove([storagePath]);redirect(path(o,"evidence-error"));}await finish(o,"evidence-saved");}
export async function downloadIncidentEvidence(f:FormData){const o=org(f),version=id.safeParse(f.get("document_version_id"));if(!version.success)redirect(path(o,"invalid"));await guard(o,"incidents.sensitive");const db=await client();const {data}=await db.from("incident_evidences").select("document_version_id,document_versions(bucket_id,storage_path)").eq("organization_id",o).eq("document_version_id",version.data).eq("visibility","sensitive").maybeSingle();const item=(data as any)?.document_versions;if(!item)redirect(path(o,"forbidden"));const signed=await db.storage.from(item.bucket_id).createSignedUrl(item.storage_path,60);if(!signed.data?.signedUrl)redirect(path(o,"evidence-error"));redirect(signed.data.signedUrl);}
