import Link from "next/link";
import { Buildings, CreditCard, Headset, Warning } from "@phosphor-icons/react/dist/ssr";
import { redirect } from "next/navigation";
import { EmptyState } from "@/components/empty-state";
import { FormDrawer } from "@/components/form-drawer";
import { PageHeader } from "@/components/page-header";
import { StatusBanner } from "@/components/status-banner";
import { StructuredData } from "@/components/structured-data";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";
import { Select } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Textarea } from "@/components/ui/textarea";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { saveSubscription, supportSession } from "@/modules/saas/actions";

type Search = { q?: string; state?: string; notice?: string };
const dateLabel = (value: string | null) => value ? new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeZone: "America/Bogota" }).format(new Date(value)) : "Sin fecha";

export default async function SaasAdmin({ searchParams }: { searchParams: Promise<Search> }) {
  const filters = await searchParams;
  const { userId, supabase } = await requireAuthenticatedUser();
  const { data: role } = await supabase.from("saas_admin_roles").select("role,status").eq("user_id", userId).maybeSingle();
  if (!role || role.status !== "active") redirect("/organizations");
  const [{ data: plans }, { data: organizations }, { data: subscriptions }, { data: sessions }] = await Promise.all([
    supabase.from("billing_plans").select("id,code,name,status,limits,feature_flags,version").order("name"),
    supabase.from("organizations").select("id,name,status").order("name"),
    supabase.from("billing_subscriptions").select("organization_id,billing_plan_id,status,trial_ends_at,current_period_start,current_period_end,commercial_note,updated_at").order("updated_at", { ascending: false }),
    supabase.from("saas_support_sessions").select("id,organization_id,status,reason,created_at,started_at,ended_at").order("created_at", { ascending: false }).limit(50),
  ]);
  const organizationName = (id: string) => organizations?.find((organization) => organization.id === id)?.name ?? "Organización no disponible";
  const planName = (id: string) => plans?.find((plan) => plan.id === id)?.name ?? "Plan no disponible";
  const filteredSubscriptions = (subscriptions ?? []).filter((subscription) => (!filters.state || filters.state === "all" || subscription.status === filters.state) && (!filters.q || organizationName(subscription.organization_id).toLowerCase().includes(filters.q.toLowerCase())));
  const activeCount = (subscriptions ?? []).filter((subscription) => subscription.status === "active" || subscription.status === "trialing").length;
  const attentionCount = (subscriptions ?? []).filter((subscription) => subscription.status === "past_due" || subscription.status === "suspended").length;
  const openSupportCount = (sessions ?? []).filter((session) => session.status === "requested" || session.status === "active").length;

  const subscriptionForm = <form action={saveSubscription} className="grid gap-4"><label className="grid gap-2 text-sm font-medium">Organización<Select name="organizationId" required>{organizations?.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</Select></label><label className="grid gap-2 text-sm font-medium">Plan<Select name="planId" required>{plans?.filter((plan) => plan.status === "active").map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · versión {plan.version}</option>)}</Select></label><label className="grid gap-2 text-sm font-medium">Estado comercial<Select name="status"><option value="trialing">En prueba</option><option value="active">Activa</option><option value="past_due">Pago pendiente</option><option value="suspended">Suspendida comercialmente</option><option value="cancelled">Cancelada</option></Select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Fin de prueba<Input name="trialEndsAt" type="datetime-local" /></label><label className="grid gap-2 text-sm font-medium">Inicio del período<Input name="periodStart" type="datetime-local" /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Fin del período<Input name="periodEnd" type="datetime-local" /></label></div><label className="grid gap-2 text-sm font-medium">Nota comercial<Textarea name="note" placeholder="Contexto auditado para el equipo interno" /></label><div className="rounded-lg border border-[var(--warning-border)] bg-[var(--warning-soft)] px-4 py-3 text-sm text-[var(--warning)]">Cambiar el estado comercial no modifica permisos, membresías ni políticas de acceso.</div><Button type="submit">Guardar estado comercial</Button></form>;
  const supportForm = <form action={supportSession} className="grid gap-4"><input type="hidden" name="action" value="request" /><input type="hidden" name="sessionId" value="" /><label className="grid gap-2 text-sm font-medium">Organización<Select name="organizationId">{organizations?.map((organization) => <option key={organization.id} value={organization.id}>{organization.name}</option>)}</Select></label><label className="grid gap-2 text-sm font-medium">Motivo<Textarea name="reason" required minLength={3} placeholder="Explica el acompañamiento solicitado y su alcance" /></label><p className="text-xs leading-5 text-[var(--muted)]">Crear una sesión no concede acceso implícito ni permite suplantar usuarios.</p><Button type="submit">Solicitar soporte</Button></form>;

  return <main className="mx-auto grid max-w-[1440px] gap-6 px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <PageHeader eyebrow="Reinova Labs · operación interna" title="Administración SaaS" description="Gestiona el estado comercial y las sesiones de soporte sin mezclar facturación con seguridad ni autorización." action={<div className="flex flex-wrap gap-2"><FormDrawer title="Nueva sesión de soporte" description="Registra el motivo antes de iniciar cualquier acompañamiento." triggerLabel="Solicitar soporte" variant="secondary">{supportForm}</FormDrawer>{role.role === "saas_admin" ? <FormDrawer title="Asignar plan o suscripción" description="Configura el ciclo comercial de una organización sin afectar sus datos ni permisos." triggerLabel="Gestionar suscripción">{subscriptionForm}</FormDrawer> : null}</div>} />
    <StatusBanner status={filters.notice} />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Resumen comercial"><KpiCard label="Organizaciones" value={organizations?.length ?? 0} icon={<Buildings size={19} />} /><KpiCard label="Activas o en prueba" value={activeCount} icon={<CreditCard size={19} />} /><KpiCard label="Requieren atención" value={attentionCount} icon={<Warning size={19} />} /><KpiCard label="Soportes abiertos" value={openSupportCount} icon={<Headset size={19} />} /></section>
    <div className="flex items-start gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm text-[var(--muted)]"><Warning size={18} className="mt-0.5 shrink-0 text-[var(--warning)]" /><p>Una suspensión comercial conserva todos los datos y no cambia los permisos de seguridad. El acceso sigue gobernado por membresías, capacidades y RLS.</p></div>
    <Card><CardHeader><CardTitle>Suscripciones</CardTitle><CardDescription>Busca una organización o filtra por estado comercial.</CardDescription></CardHeader><CardContent><form className="mb-5 grid gap-3 sm:grid-cols-[1fr_220px_auto]"><Input name="q" defaultValue={filters.q} placeholder="Buscar organización" aria-label="Buscar organización" /><Select name="state" defaultValue={filters.state ?? "all"} aria-label="Estado comercial"><option value="all">Todos los estados</option><option value="trialing">En prueba</option><option value="active">Activa</option><option value="past_due">Pago pendiente</option><option value="suspended">Suspendida</option><option value="cancelled">Cancelada</option></Select><Button type="submit" variant="secondary">Aplicar filtros</Button></form>{filteredSubscriptions.length ? <div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{filteredSubscriptions.map((subscription) => { const plan = plans?.find((item) => item.id === subscription.billing_plan_id); return <article key={subscription.organization_id} className="grid gap-4 py-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(280px,.7fr)]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{organizationName(subscription.organization_id)}</h3><StatusBadge>{subscription.status}</StatusBadge></div><p className="mt-1 text-sm text-[var(--muted)]">{planName(subscription.billing_plan_id)} · período {dateLabel(subscription.current_period_start)} — {dateLabel(subscription.current_period_end)}</p>{subscription.trial_ends_at ? <p className="mt-1 text-sm text-[var(--muted)]">Prueba hasta {dateLabel(subscription.trial_ends_at)}</p> : null}{subscription.commercial_note ? <p className="mt-3 max-w-2xl text-sm leading-6">{subscription.commercial_note}</p> : null}</div>{plan ? <details className="rounded-lg border border-[var(--border)] px-3 py-2"><summary className="cursor-pointer text-sm font-semibold">Límites y capacidades comerciales</summary><div className="mt-3 grid gap-3"><StructuredData value={plan.limits} /><StructuredData value={plan.feature_flags} /></div></details> : null}</article>; })}</div> : <EmptyState title="No hay suscripciones para esta búsqueda" description="Ajusta los filtros o asigna un plan desde la acción principal." />}</CardContent></Card>
    <Card><CardHeader><CardTitle>Soporte auditado</CardTitle><CardDescription>Una sesión requiere motivo, inicio y cierre explícitos. Las sesiones finalizadas no se reabren.</CardDescription></CardHeader><CardContent>{sessions?.length ? <div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{sessions.map((session) => <article key={session.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{organizationName(session.organization_id)}</p><StatusBadge>{session.status}</StatusBadge></div><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{session.reason}</p><p className="mt-1 text-xs text-[var(--muted)]">Solicitada {dateLabel(session.created_at)}</p></div>{session.status === "requested" || session.status === "active" ? <form action={supportSession}><input type="hidden" name="organizationId" value={session.organization_id} /><input type="hidden" name="sessionId" value={session.id} /><input type="hidden" name="reason" value={session.reason} /><Button name="action" value={session.status === "requested" ? "start" : "end"} size="sm" variant={session.status === "requested" ? "primary" : "secondary"}>{session.status === "requested" ? "Iniciar sesión" : "Finalizar sesión"}</Button></form> : <span className="text-xs text-[var(--muted)]">Finalizada {dateLabel(session.ended_at)}</span>}</article>)}</div> : <EmptyState title="No hay sesiones de soporte" description="Registra una solicitud cuando una organización necesite acompañamiento." />}</CardContent></Card>
    <p className="text-center text-xs text-[var(--muted)]"><Link href="/organizations" className="font-semibold text-[var(--brand)] hover:underline">Volver a organizaciones</Link></p>
  </main>;
}
