import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { StatusBanner } from "@/components/status-banner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/server";
import { can } from "@/modules/auth/permissions";
import { uploadDocument } from "@/modules/organizations/core-actions";
import { requireTenant } from "@/modules/organizations/tenant";

export default async function DocumentsPage({ params, searchParams }: { params: Promise<{ organizationId: string }>; searchParams: Promise<{ status?: string; q?: string; state?: string; page?: string }> }) {
  const { organizationId } = await params; await requireTenant(organizationId);
  const { status, q = "", state = "active", page = "1" } = await searchParams;
  const currentPage = Math.max(1, Number.parseInt(page, 10) || 1); const pageSize = 12;
  const supabase = await createClient();
  let query = supabase.from("documents").select("id,title,status,expires_at,created_at,entity_type", { count: "exact" }).eq("organization_id", organizationId).neq("status", "deleted").order("created_at", { ascending: false });
  if (state !== "all") query = query.eq("status", state);
  if (q.trim()) query = query.ilike("title", `%${q.trim().replace(/[%_]/g, "")}%`);
  const [documents, mayUpload, mayRead] = await Promise.all([query.range((currentPage - 1) * pageSize, currentPage * pageSize - 1), can(organizationId, "documents.create"), can(organizationId, "documents.read")]);
  const totalPages = Math.max(1, Math.ceil((documents.count ?? 0) / pageSize));
  const pageHref = (next: number) => `/org/${organizationId}/documents?${new URLSearchParams({ ...(q ? { q } : {}), ...(state !== "active" ? { state } : {}), page: String(next) }).toString()}`;
  if (!mayRead) return <div className="grid gap-7"><PageHeader title="Documentos y evidencias" description="Archivos privados y aislados por organización." /><StatusBanner status={status} /><Card><CardContent className="py-10 text-sm text-[var(--muted)]">No tienes permiso para consultar documentos de esta organización.</CardContent></Card></div>;
  return <div className="grid gap-7"><PageHeader title="Documentos y evidencias" description="Archivos privados, versionables y aislados por organización." /><StatusBanner status={status} />{mayUpload ? <Card><CardHeader><h2 className="font-semibold">Cargar documento</h2></CardHeader><CardContent><form action={uploadDocument} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="organizationId" value={organizationId} /><label className="grid gap-1 text-sm font-medium sm:col-span-2">Título<Input name="title" required /></label><label className="grid gap-1 text-sm font-medium">Tipo de entidad<Input name="entity_type" defaultValue="organization" required /></label><label className="grid gap-1 text-sm font-medium">ID de entidad<Input name="entity_id" required /></label><label className="grid gap-1 text-sm font-medium">Vencimiento (opcional)<Input name="expires_at" type="datetime-local" /></label><label className="grid gap-1 text-sm font-medium">Archivo PDF o imagen<Input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required /></label><div className="sm:col-span-2"><Button type="submit">Cargar archivo privado</Button></div></form></CardContent></Card> : null}<Card><CardHeader><h2 className="font-semibold">Registro</h2></CardHeader><CardContent className="grid gap-4"><form className="grid gap-3 sm:grid-cols-[1fr_10rem_auto]"><Input name="q" defaultValue={q} placeholder="Buscar por título" aria-label="Buscar documentos" /><select name="state" defaultValue={state} className="min-h-10 rounded-md border border-[var(--border)] bg-white px-3 text-sm"><option value="active">Activos</option><option value="archived">Archivados</option><option value="all">Todos</option></select><Button type="submit">Filtrar</Button></form>{documents.data?.length ? documents.data.map((d) => <Link key={d.id} href={`/org/${organizationId}/documents/${d.id}`} className="rounded-lg border border-[var(--border)] p-3 outline-none transition hover:border-[var(--brand)] focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"><strong>{d.title}</strong><p className="mt-1 text-sm text-[var(--muted)]">{d.entity_type} · {d.status}{d.expires_at ? ` · vence ${new Date(d.expires_at).toLocaleDateString("es-CO")}` : ""}</p></Link>) : <p className="py-6 text-sm text-[var(--muted)]">No hay documentos para los filtros actuales.</p>}{totalPages > 1 ? <nav aria-label="Paginación de documentos" className="flex items-center justify-end gap-3 text-sm"><Link aria-disabled={currentPage === 1} className="text-[var(--brand)]" href={pageHref(Math.max(1, currentPage - 1))}>Anterior</Link><span className="text-[var(--muted)]">Página {currentPage} de {totalPages}</span><Link aria-disabled={currentPage === totalPages} className="text-[var(--brand)]" href={pageHref(Math.min(totalPages, currentPage + 1))}>Siguiente</Link></nav> : null}</CardContent></Card></div>;
}
