/* eslint-disable @typescript-eslint/no-explicit-any */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/empty-state";
import { can } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { commitImport, rollbackImport, stageImport } from "@/modules/imports/actions";
import { targetLabels, templateColumns, type ImportTarget } from "@/modules/imports/schemas";

const targets = Object.keys(targetLabels) as ImportTarget[];
const mappingFields = ["legal_name", "tax_id", "name", "code", "legal_entity_tax_id", "site_code", "employee_code", "first_name", "last_name", "work_email", "area_code", "status"];

export default async function ImportsPage({ params, searchParams }: { params: Promise<{ organizationId: string }>; searchParams: Promise<{ status?: string }> }) {
  const { organizationId } = await params; const filters = await searchParams; const { supabase } = await requireAuthenticatedUser(); const db = supabase as any;
  const [read, manage, jobsR] = await Promise.all([can(organizationId, "imports.read"), can(organizationId, "imports.manage"), db.from("import_jobs").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }).limit(25)]);
  if (!read && !manage) return <EmptyState title="Sin permiso" description="Solicita acceso a importaciones."/>;
  const jobs = jobsR.data ?? []; const previewId = (filters.status ?? "").startsWith("preview-") ? (filters.status ?? "").slice(8) : null; const preview = previewId ? jobs.find((job: any) => job.id === previewId) : null;
  const rowsR = preview ? await db.from("import_rows").select("row_number,normalized_data,validation_errors,status").eq("organization_id", organizationId).eq("import_job_id", preview.id).order("row_number").limit(25) : { data: [] };
  return <main className="grid gap-5 p-6">
    <div><p className="eyebrow">Datos estructurados</p><h1 className="page-title">Importaciones</h1><p className="page-description">Carga estructura o nómina mínima desde CSV/XLSX. No importes datos clínicos, financieros ni de identidad.</p></div>
    {filters.status ? <p className="rounded border p-3 text-sm">Estado: {filters.status.replaceAll("-", " ")}</p> : null}
    {manage ? <Card><CardHeader><CardTitle>Nuevo archivo</CardTitle></CardHeader><CardContent><form action={stageImport} className="grid gap-3 lg:grid-cols-3"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1 text-sm">Entidad<select name="target" defaultValue="worker"><option value="worker">Trabajadores</option><option value="legal_entity">Razones sociales</option><option value="site">Sedes</option><option value="area">Áreas</option></select></label><label className="grid gap-1 text-sm">Archivo CSV/XLSX<input className="h-10 rounded-lg border border-[var(--border)] px-3" name="file" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required/></label><div className="flex items-end"><Button>Analizar y previsualizar</Button></div><p className="lg:col-span-3 text-sm text-[var(--muted)]">Límite: 10 MB, una hoja XLSX, 1.000 filas y 50 columnas. Los encabezados estándar se mapean automáticamente.</p><details className="lg:col-span-3 rounded border p-3 text-sm"><summary className="cursor-pointer font-medium">Mapeo manual de encabezados</summary><div className="mt-3 grid gap-2 sm:grid-cols-3">{mappingFields.map((field) => <label key={field} className="grid gap-1 text-xs">{field}<input name={field} placeholder={field} className="h-9 rounded border border-[var(--border)] px-2"/></label>)}</div></details></form><div className="mt-4 grid gap-2 text-sm">{targets.map((target) => <p key={target}><b>{targetLabels[target]}:</b> {templateColumns[target].join(", ")} · <a className="underline" href={`/org/${organizationId}/imports/template/${target}`}>plantilla CSV</a></p>)}</div></CardContent></Card> : null}
    {preview ? <Card><CardHeader><CardTitle>Previsualización: {targetLabels[preview.target_entity_type as ImportTarget]}</CardTitle></CardHeader><CardContent className="grid gap-3"><p className="text-sm">{preview.summary?.valid_rows ?? 0} filas válidas · {preview.summary?.invalid_rows ?? 0} con errores. Solo se confirma si no quedan errores.</p>{(preview.summary?.invalid_rows ?? 0) > 0 ? <a className="text-sm underline" href={`/org/${organizationId}/imports/${preview.id}/errors`}>Descargar errores CSV</a> : null}<div className="max-h-72 overflow-auto rounded border p-2 text-xs">{(rowsR.data ?? []).map((row: any) => <div key={row.row_number} className="border-b py-1"><b>Fila {row.row_number}</b> · {row.status} · {row.validation_errors?.length ? JSON.stringify(row.validation_errors) : JSON.stringify(row.normalized_data)}</div>)}</div>{manage ? <form action={commitImport}><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="id" value={preview.id}/><Button disabled={(preview.summary?.invalid_rows ?? 0) > 0}>Confirmar importación</Button></form> : null}</CardContent></Card> : null}
    <section className="grid gap-3"><h2 className="text-lg font-semibold">Historial</h2>{jobs.length ? jobs.map((job: any) => <Card key={job.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 pt-5"><div><b>{targetLabels[job.target_entity_type as ImportTarget] ?? job.import_type}</b><p className="text-sm text-[var(--muted)]">{job.file_name} · {job.status} · {new Date(job.created_at).toLocaleString("es-CO")}</p><p className="text-xs text-[var(--muted)]">{job.summary?.imported_rows ?? 0} importadas · conflictos de reversión: {job.summary?.rollback_conflicts ?? 0}</p></div>{manage && job.status === "completed" ? <form action={rollbackImport}><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="id" value={job.id}/><Button variant="secondary">Revertir lógicamente</Button></form> : null}</CardContent></Card>) : <EmptyState title="Sin importaciones" description="Carga un archivo para crear una previsualización segura."/>}</section>
  </main>;
}
