"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { redirect } from "next/navigation";import { revalidatePath } from "next/cache";import { z } from "zod";import {can} from "@/modules/auth/permissions";import {requireAuthenticatedUser} from "@/modules/organizations/tenant";import {contactSchema,contractorSchema,contractSchema,portalAccessSchema,requirementSchema,approvalSchema} from "./schemas";
const oid=z.uuid(),route=(o:string,s:string)=>`/org/${o}/contractors?status=${s}`,data=(f:FormData)=>Object.fromEntries(f);async function permit(o:string,p:any){if(!(await can(o,p)))redirect(route(o,"forbidden"));}async function client(){return (await requireAuthenticatedUser()).supabase as any}const done=(o:string,s:string)=>{revalidatePath(`/org/${o}/contractors`);redirect(route(o,s));};
export async function createContractor(f:FormData){const o=oid.parse(f.get("organizationId")),x=contractorSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.manage");const {error}=await (await client()).from("contractor_organizations").insert({organization_id:o,...x.data});done(o,error?"error":"saved");}
export async function createContact(f:FormData){const o=oid.parse(f.get("organizationId")),x=contactSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.manage");const {error}=await (await client()).from("contractor_contacts").insert({organization_id:o,...x.data});done(o,error?"error":"saved");}
export async function createContract(f:FormData){const o=oid.parse(f.get("organizationId")),x=contractSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.manage");const {error}=await (await client()).from("contracts").insert({organization_id:o,...x.data});done(o,error?"error":"saved");}
export async function createRequirement(f:FormData){const o=oid.parse(f.get("organizationId")),x=requirementSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.manage");const {error}=await (await client()).from("contract_document_requirements").insert({organization_id:o,...x.data});done(o,error?"error":"saved");}
export async function provisionPortal(f:FormData){const o=oid.parse(f.get("organizationId")),x=portalAccessSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.approve");const {error}=await (await client()).functions.invoke("provision-contractor-portal",{body:{organizationId:o,contactId:x.data.contact_id,contractId:x.data.contract_id,siteId:x.data.site_id,activate:x.data.activate}});done(o,error?"portal-error":"portal-saved");}
export async function approveSubmission(f:FormData){const o=oid.parse(f.get("organizationId")),x=approvalSchema.safeParse(data(f));if(!x.success)redirect(route(o,"invalid"));await permit(o,"contractors.approve");const {userId}=await requireAuthenticatedUser();const {error}=await (await client()).from("contract_document_submissions").update({status:x.data.status,review_note:x.data.note??null,reviewed_by:userId}).eq("organization_id",o).eq("id",x.data.id);done(o,error?"error":"approved");}
export async function submitContractorDocument(f:FormData){const requirementId=z.uuid().safeParse(f.get("requirementId"));const organizationId=z.uuid().safeParse(f.get("organizationId"));const file=f.get("file");if(!requirementId.success||!organizationId.success||!(file instanceof File)||file.size<1||file.size>26214400||!["application/pdf","image/jpeg","image/png","image/webp"].includes(file.type))redirect("/contractor-portal?status=invalid");const {userId,supabase}=await requireAuthenticatedUser();const db=supabase as any;const {data:req}=await db.from("contract_document_requirements").select("id,organization_id").eq("id",requirementId.data).eq("organization_id",organizationId.data).maybeSingle();if(!req)redirect("/contractor-portal?status=forbidden");const documentId=crypto.randomUUID(),versionId=crypto.randomUUID(),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_")||"evidencia",path=`${organizationId.data}/contract_document_requirement/${requirementId.data}/${documentId}/${safe}`;const upload=await db.storage.from("evidences").upload(path,file,{contentType:file.type,upsert:false});if(upload.error)redirect("/contractor-portal?status=error");const doc=await db.from("documents").insert({id:documentId,organization_id:organizationId.data,entity_type:"contract_document_requirement",entity_id:requirementId.data,title:`Requisito contratista · ${file.name}`,created_by:userId,updated_by:userId});const ver=doc.error?{error:doc.error}:await db.from("document_versions").insert({id:versionId,organization_id:organizationId.data,document_id:documentId,version_number:1,bucket_id:"evidences",storage_path:path,original_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:userId});if(ver.error){await db.storage.from("evidences").remove([path]);redirect("/contractor-portal?status=error");}const submission=await db.from("contract_document_submissions").insert({organization_id:organizationId.data,contract_document_requirement_id:requirementId.data,document_version_id:versionId,submitted_by:userId});if(submission.error){await db.storage.from("evidences").remove([path]);redirect("/contractor-portal?status=error");}redirect("/contractor-portal?status=submitted");}
