import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { createClient } from "@/lib/supabase/server";
import { can } from "@/modules/auth/permissions";
import { addTaskComment, addTaskDependency, approvePlan, attachTaskEvidence, createActivity, createPlan, createTask, setTaskStatus } from "@/modules/organizations/planning-actions";
import { requireTenant } from "@/modules/organizations/tenant";

const utc = (v:string|null) => v ? new Date(v).toLocaleString("es-CO", { timeZone: "UTC", timeZoneName: "short" }) : "Sin vencimiento";
export default async function PlanningPage({params,searchParams}:{params:Promise<{organizationId:string}>;searchParams:Promise<{q?:string;status?:string;view?:string}>}) {
 const {organizationId}=await params; await requireTenant(organizationId); const {q="",status="all",view="board"}=await searchParams; const [read,manage,approve,supabase]=await Promise.all([can(organizationId,"planning.read"),can(organizationId,"planning.manage"),can(organizationId,"tasks.approve"),createClient()]); if(!read)return <EmptyState title="Sin permiso" description="Solicita acceso a planificación."/>;
 let tasksQ=supabase.from("tasks").select("id,title,description,status,priority,due_at,assigned_to,annual_plan_id,plan_activity_id,improvement_action_id,recurrence_rule_id").eq("organization_id",organizationId).order("due_at",{ascending:true});if(q)tasksQ=tasksQ.ilike("title",`%${q.replace(/[%_]/g,"")}%`);if(status!=="all")tasksQ=tasksQ.eq("status",status);const [plansR,actsR,tasksR,membersR,versionsR,depsR,commentsR,improvementR]=await Promise.all([supabase.from("annual_plans").select("*").eq("organization_id",organizationId).order("year",{ascending:false}),supabase.from("plan_activities").select("*").eq("organization_id",organizationId),tasksQ,supabase.from("organization_members").select("user_id").eq("organization_id",organizationId).eq("status","active"),supabase.from("document_versions").select("id,original_name").eq("organization_id",organizationId).limit(60),supabase.from("task_dependencies").select("task_id,depends_on_task_id").eq("organization_id",organizationId),supabase.from("task_comments").select("task_id,body,created_at").eq("organization_id",organizationId).order("created_at",{ascending:false}),supabase.from("improvement_actions").select("id,title").eq("organization_id",organizationId).neq("status","cancelled")]); const plans=plansR.data??[],activities=actsR.data??[],tasks=tasksR.data??[],members=membersR.data??[],versions=versionsR.data??[],deps=depsR.data??[],comments=commentsR.data??[],improvementActions=improvementR.data??[];
 void improvementActions;
 const taskOptions=tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>); const hidden=(id:string)=><input type="hidden" name="organizationId" value={id}/>;
 return <div className="grid gap-6"><PageHeader eyebrow="Plan anual" title="Planificación y tareas" description="Planifica, ejecuta y evidencia acciones con fechas UTC, dependencias y trazabilidad."/>
 {manage?<div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><b>Nuevo plan anual</b></CardHeader><CardContent><form action={createPlan} className="grid gap-2">{hidden(organizationId)}<Input name="year" type="number" defaultValue={new Date().getUTCFullYear()} aria-label="Año"/><Input name="name" placeholder="Plan anual SG-SST" aria-label="Nombre del plan"/><Input name="budget" type="number" min="0" step="0.01" placeholder="Presupuesto opcional" aria-label="Presupuesto"/><Button>Crear plan</Button></form></CardContent></Card><Card><CardHeader><b>Nueva actividad</b></CardHeader><CardContent><form action={createActivity} className="grid gap-2">{hidden(organizationId)}<Select name="plan_id" aria-label="Plan anual">{plans.map(p=><option key={p.id} value={p.id}>{p.year} · {p.name}</option>)}</Select><Input name="title" placeholder="Actividad" aria-label="Actividad"/><Select name="priority" defaultValue="medium" aria-label="Prioridad"><option value="critical">Crítica</option><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></Select><Select name="responsible_user_id" aria-label="Responsable"><option value="">Sin asignar</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.user_id}</option>)}</Select><Button>Agregar actividad</Button></form></CardContent></Card><Card><CardHeader><b>Nueva tarea</b></CardHeader><CardContent><form action={createTask} className="grid gap-2">{hidden(organizationId)}<Input name="title" placeholder="Tarea" aria-label="Tarea"/><Textarea name="description" placeholder="Descripción" aria-label="Descripción"/><Select name="annual_plan_id" aria-label="Plan asociado"><option value="">Sin plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Select name="plan_activity_id" aria-label="Actividad asociada"><option value="">Sin actividad</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</Select><Select name="improvement_action_id" aria-label="Acción de mejora origen"><option value="">Sin acción de mejora</option></Select><Input name="due_at" type="datetime-local" aria-label="Vencimiento UTC"/><Select name="recurrence_frequency" defaultValue="none" aria-label="Recurrencia"><option value="none">Sin recurrencia</option><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option><option value="yearly">Anual</option></Select><Input name="recurrence_interval" defaultValue="1" type="number" min="1" aria-label="Intervalo"/><Button>Crear tarea</Button></form></CardContent></Card></div>:null}
 <form className="flex gap-2" method="get"><Input name="q" defaultValue={q} placeholder="Buscar tareas" aria-label="Buscar tareas"/><Select name="status" defaultValue={status} aria-label="Estado"><option value="all">Todos</option>{["todo","in_progress","blocked","completed","cancelled"].map(s=><option key={s}>{s}</option>)}</Select><Select name="view" defaultValue={view} aria-label="Vista"><option value="board">Tablero</option><option value="calendar">Calendario</option></Select><Button variant="secondary">Filtrar</Button></form>
 <section className={view==="board"?"grid gap-4 lg:grid-cols-3":"grid gap-4"}>{tasks.length?tasks.map(t=><Card key={t.id}><CardHeader><div className="flex justify-between gap-2"><b>{t.title}</b><Badge>{t.status}</Badge></div></CardHeader><CardContent className="grid gap-3"><p className="text-sm">{t.description}</p><p className="text-xs text-[var(--muted)]">{view==="calendar"?`Calendario UTC: ${utc(t.due_at)}`:`Vence: ${utc(t.due_at)}`} · {t.recurrence_rule_id?"Recurrente":"Única"}</p><p className="text-xs">Dependencias: {deps.filter(d=>d.task_id===t.id).length} · Comentarios: {comments.filter(c=>c.task_id===t.id).length}</p><form action={setTaskStatus} className="flex gap-2">{hidden(organizationId)}<input type="hidden" name="task_id" value={t.id}/><Select name="status" defaultValue={t.status} aria-label={`Estado ${t.title}`}><option>todo</option><option>in_progress</option><option>blocked</option><option>completed</option><option>cancelled</option></Select><Button size="sm">Actualizar</Button></form>{manage?<><form action={addTaskDependency} className="flex gap-2">{hidden(organizationId)}<input type="hidden" name="task_id" value={t.id}/><Select name="depends_on_task_id" aria-label={`Dependencia ${t.title}`}><option value="">Selecciona</option>{taskOptions}</Select><Button size="sm" variant="secondary">Depender</Button></form><form action={addTaskComment} className="flex gap-2">{hidden(organizationId)}<input type="hidden" name="task_id" value={t.id}/><Input name="body" aria-label={`Comentario ${t.title}`} placeholder="Comentario"/><Button size="sm" variant="secondary">Comentar</Button></form><form action={attachTaskEvidence} className="flex gap-2">{hidden(organizationId)}<input type="hidden" name="task_id" value={t.id}/><Select name="document_version_id" aria-label={`Evidencia ${t.title}`}><option value="">Documento</option>{versions.map(v=><option key={v.id} value={v.id}>{v.original_name}</option>)}</Select><Button size="sm" variant="secondary">Evidenciar</Button></form></>:null}</CardContent></Card>):<EmptyState title="No hay tareas" description="Crea una tarea desde el plan, una actividad o una acción de mejora."/>}</section>
 <section className="grid gap-3">{plans.map(p=><Card key={p.id}><CardContent className="flex items-center justify-between"><span><b>{p.year} · {p.name}</b> · {p.status} · presupuesto {p.budget??"—"}</span>{approve&&p.status!=="approved"?<form action={approvePlan}>{hidden(organizationId)}<input type="hidden" name="plan_id" value={p.id}/><Button size="sm">Aprobar plan</Button></form>:null}</CardContent></Card>)}</section></div>;
}
