"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { can, type PermissionCode } from "@/modules/auth/permissions";
import { activitySchema, commentSchema, dependencySchema, evidenceSchema, planSchema, statusSchema, taskSchema } from "./planning-schemas";
import { requireAuthenticatedUser } from "./tenant";
import { z } from "zod";
const tenant = z.uuid(); const route=(o:string,s:string)=>`/org/${o}/planning?status=${s}`;
async function allowed(o:string,p:PermissionCode){if(!(await can(o,p)))redirect(`/org/${o}/dashboard?error=forbidden`);}
const refresh=(o:string)=>revalidatePath(`/org/${o}/planning`);
export async function createPlan(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=planSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("annual_plans").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?.code==="23505"?"conflict":error?"error":"created"));}
export async function createActivity(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=activitySchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");const {userId,supabase}=await requireAuthenticatedUser();const {data:plan}=await supabase.from("annual_plans").select("id").eq("organization_id",o).eq("id",x.data.plan_id).maybeSingle();if(!plan)redirect(route(o,"notfound"));const {plan_id,...activity}=x.data;const {error}=await supabase.from("plan_activities").insert({organization_id:o,annual_plan_id:plan_id,...activity,created_by:userId});refresh(o);redirect(route(o,error?"error":"created"));}
export async function createTask(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=taskSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");const {userId,supabase}=await requireAuthenticatedUser();let recurrence_rule_id:null|string=null;let occurrence_at:null|string=null;let occurrence_key:null|string=null;if(x.data.recurrence_frequency!=="none"){const start=x.data.due_at??new Date().toISOString();const r=await supabase.from("task_recurrence_rules").insert({organization_id:o,frequency:x.data.recurrence_frequency,interval_count:x.data.recurrence_interval,starts_at:start,ends_at:x.data.recurrence_ends_at,timezone:"UTC"}).select("id").single();if(r.error)redirect(route(o,"error"));recurrence_rule_id=r.data.id;occurrence_at=start;occurrence_key=`${r.data.id}:${new Date(start).toISOString()}`;}const {error}=await supabase.from("tasks").insert({organization_id:o,title:x.data.title,description:x.data.description,priority:x.data.priority,assigned_to:x.data.assigned_to,due_at:x.data.due_at,annual_plan_id:x.data.annual_plan_id,plan_activity_id:x.data.plan_activity_id,improvement_action_id:x.data.improvement_action_id,recurrence_rule_id,occurrence_at,occurrence_key,created_by:userId});refresh(o);redirect(route(o,error?"error":"created"));}
export async function setTaskStatus(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=statusSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));const {userId,supabase}=await requireAuthenticatedUser();const {data:t}=await supabase.from("tasks").select("assigned_to").eq("organization_id",o).eq("id",x.data.task_id).maybeSingle();if(!t)redirect(route(o,"notfound"));if(t.assigned_to===userId)await allowed(o,"tasks.update_status");else await allowed(o,"planning.manage");const {error}=await supabase.from("tasks").update({status:x.data.status}).eq("organization_id",o).eq("id",x.data.task_id);refresh(o);redirect(route(o,error?"transition":"saved"));}
export async function addTaskDependency(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=dependencySchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");const {supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("task_dependencies").insert({organization_id:o,...x.data});refresh(o);redirect(route(o,error?"dependency":"saved"));}
export async function addTaskComment(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=commentSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("task_comments").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function attachTaskEvidence(f:FormData){const o=tenant.parse(f.get("organizationId"));const x=evidenceSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await allowed(o,"planning.manage");if(!(await can(o,"documents.read")))redirect(route(o,"forbidden"));const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("task_evidences").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"evidence":"saved"));}
export async function approvePlan(f:FormData){const o=tenant.parse(f.get("organizationId"));const planId=z.uuid().safeParse(f.get("plan_id"));if(!planId.success)redirect(route(o,"error"));await allowed(o,"tasks.approve");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("annual_plans").update({status:"approved",approved_at:new Date().toISOString(),approved_by:userId}).eq("organization_id",o).eq("id",planId.data);refresh(o);redirect(route(o,error?"error":"approved"));}
