"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { z } from "zod";import { can } from "@/modules/auth/permissions";import { activitySchema,assessmentSchema,controlSchema,identificationSchema,processSchema,taskSchema } from "./risk-schemas";import { requireAuthenticatedUser } from "./tenant";import type { Json } from "@/types/database";
const tid=z.uuid(),route=(o:string,s:string)=>`/org/${o}/risks?status=${s}`;async function guard(o:string,p:"risks.manage"|"risks.validate"){if(!(await can(o,p)))redirect(`/org/${o}/dashboard?error=forbidden`)}const refresh=(o:string)=>revalidatePath(`/org/${o}/risks`);
export async function createRiskProcess(f:FormData){const o=tid.parse(f.get("organizationId")),x=processSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("processes").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function createRiskActivity(f:FormData){const o=tid.parse(f.get("organizationId")),x=activitySchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("activities").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function createRiskTask(f:FormData){const o=tid.parse(f.get("organizationId")),x=taskSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("risk_tasks").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function createRiskIdentification(f:FormData){const o=tid.parse(f.get("organizationId")),x=identificationSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("risk_identifications").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function createRiskControl(f:FormData){const o=tid.parse(f.get("organizationId")),x=controlSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");const {userId,supabase}=await requireAuthenticatedUser();const {error}=await supabase.from("risk_controls").insert({organization_id:o,...x.data,created_by:userId});refresh(o);redirect(route(o,error?"error":"saved"));}
export async function createRiskAssessment(f:FormData){const o=tid.parse(f.get("organizationId")),x=assessmentSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"error"));await guard(o,"risks.manage");let input_data:Json;try{input_data=JSON.parse(x.data.input_data) as Json;}catch{redirect(route(o,"error"));}const {supabase}=await requireAuthenticatedUser();const {data:version}=await supabase.from("risk_methodology_versions").select("id,status,expert_review_status").eq("id",x.data.risk_methodology_version_id).maybeSingle();if(!version||version.status!=="approved"||version.expert_review_status!=="reviewed")redirect(route(o,"methodology-pending"));const {data,error}=await supabase.from("risk_assessments").insert({organization_id:o,risk_identification_id:x.data.risk_identification_id,risk_methodology_version_id:x.data.risk_methodology_version_id,parent_risk_assessment_id:x.data.parent_risk_assessment_id,input_data,status:"in_progress"}).select("id").single();if(error||!data)redirect(route(o,"error"));const {error:calc}=await (supabase as unknown as {rpc:(fn:string,args:unknown)=>Promise<{error:unknown}>}).rpc("calculate_risk_assessment",{p_assessment_id:data.id});refresh(o);redirect(route(o,calc?"error":"calculated"));}
