"use server";
import { revalidatePath } from "next/cache";
import { can } from "@/modules/auth/permissions";
import { askOpenAi, copilotConfig } from "@/modules/copilot/openai";
import { retrieveAuthorizedContext } from "@/modules/copilot/retrieval";
import { hasPromptInjectionPattern, safeContext } from "@/modules/copilot/security";
import { decisionSchema, proposalSchema, questionSchema } from "@/modules/copilot/schemas";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { createHash } from "crypto";
async function access(org: string, permission: "copilot.read"|"copilot.manage"|"copilot.confirm_critical") { if (!(await can(org,permission))) throw new Error("No tienes permiso para esta operación de Copilot."); }
export async function askCopilot(form: FormData) { const input=questionSchema.parse({organizationId:form.get("organizationId"),conversationId:form.get("conversationId")||undefined,question:form.get("question")}); await access(input.organizationId,"copilot.read"); const {supabase}=await requireAuthenticatedUser(); let conversationId=input.conversationId;
 if (!conversationId) { const {data,error}=await supabase.rpc("create_copilot_conversation" as never,{p_organization_id:input.organizationId,p_title:input.question.slice(0,80)} as never); if(error) throw new Error("No fue posible crear la conversación."); conversationId=(data as {id:string}).id; }
 const flagged=hasPromptInjectionPattern(input.question); const {data:userMessage,error:userError}=await supabase.rpc("record_copilot_user_message" as never,{p_conversation_id:conversationId,p_content:input.question,p_prompt_injection_flag:flagged} as never); if(userError) throw new Error("No fue posible registrar la pregunta.");
 const sources=await retrieveAuthorizedContext(input.organizationId); const context=sources.map(s=>`[${s.source_label}] ${safeContext(s.excerpt)}`).join("\n").slice(0,5000); let result; try { result=await askOpenAi(input.question,context); } catch (error) { const e=error as {status?:number;code?:string;name?:string}; console.error("copilot_provider_error", { status:e.status ?? null, code:e.code ?? null, name:e.name ?? "Error", model:copilotConfig()?.model ?? null }); result={text:"No fue posible contactar el proveedor de IA. Intenta nuevamente más tarde.",responseId:null,blocked:false}; }
 const config=copilotConfig(); const hash=createHash("sha256").update(`${conversationId}:${(userMessage as {id:string}).id}:${input.question}`).digest("hex"); const {error}=await supabase.rpc("record_copilot_response" as never,{p_conversation_id:conversationId,p_user_message_id:(userMessage as {id:string}).id,p_content:result.text,p_prompt_injection_flag:flagged||sources.some(s=>hasPromptInjectionPattern(s.excerpt)),p_provider:"openai",p_model:config?.model??"configuration_unavailable",p_status:result.blocked?"blocked":"completed",p_request_hash:hash,p_provider_response_id:result.responseId,p_error_code:result.blocked?"configuration_missing":null,p_sources:sources} as never); if(error) throw new Error("No fue posible guardar la respuesta de forma segura."); revalidatePath(`/org/${input.organizationId}/copilot`); }
export async function createProposal(form: FormData) { const input=proposalSchema.parse({organizationId:form.get("organizationId"),conversationId:form.get("conversationId"),proposalType:form.get("proposalType"),summary:form.get("summary")}); await access(input.organizationId,"copilot.manage"); const {supabase}=await requireAuthenticatedUser(); const {error}=await supabase.rpc("create_copilot_proposal" as never,{p_conversation_id:input.conversationId,p_proposal_type:input.proposalType,p_proposal:{summary:input.summary,execution:"none"}} as never); if(error) throw new Error("No fue posible registrar la propuesta."); revalidatePath(`/org/${input.organizationId}/copilot`); }
export async function decideProposal(form: FormData) { const input=decisionSchema.parse({organizationId:form.get("organizationId"),proposalId:form.get("proposalId"),status:form.get("status"),note:form.get("note")}); await access(input.organizationId,"copilot.manage"); const {supabase}=await requireAuthenticatedUser(); const {error}=await supabase.rpc("decide_copilot_proposal" as never,{p_proposal_id:input.proposalId,p_status:input.status,p_decision_note:input.note} as never); if(error) throw new Error("No fue posible registrar la decisión humana."); revalidatePath(`/org/${input.organizationId}/copilot`); }
