/* eslint-disable @typescript-eslint/no-explicit-any */
import { EmptyState } from "@/components/empty-state";
import { FormDrawer } from "@/components/form-drawer";
import { OperationsNav } from "@/components/operations-nav";
import { PageHeader } from "@/components/page-header";
import { StatusBanner } from "@/components/status-banner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/ui/kpi-card";
import { Select } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/status-badge";
import { Textarea } from "@/components/ui/textarea";
import { can } from "@/modules/auth/permissions";
import { addWorkRestriction, createHealthDecision, createHealthProgram, enrollHealthProgram, recordFitness, resolveHealthDecision } from "@/modules/occupational-health/actions";
import { displayPersonName } from "@/modules/organizations/directory";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";

const conceptLabels: Record<string, string> = { fit: "Apto", fit_with_restrictions: "Apto con restricciones", pending_review: "Pendiente de revisión", not_issued: "No emitido" };
const decisionLabels: Record<string, string> = { accommodation: "Adecuación del trabajo", work_assignment_review: "Revisión de asignación", restriction_acknowledgement: "Reconocimiento de restricción" };
const displayDate = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "Sin fecha";

export default async function OccupationalHealthPage({ params, searchParams }: {
  params: Promise<{ organizationId: string }>;
  searchParams: Promise<{ status?: string }>;
}) {
  const { organizationId } = await params;
  const { status } = await searchParams;
  const { supabase } = await requireAuthenticatedUser();
  const db = supabase as any;
  const [read, manage, medical, hr, confirm, membersR] = await Promise.all([
    can(organizationId, "occupational_health.read"), can(organizationId, "occupational_health.manage"), can(organizationId, "occupational_health.medical"), can(organizationId, "occupational_health.hr_sensitive"), can(organizationId, "occupational_health.confirm"),
    db.from("organization_members").select("id,user_id").eq("organization_id", organizationId).eq("status", "active"),
  ]);
  if (!read && !manage && !medical && !hr) return <EmptyState title="Sin acceso a salud ocupacional" description="Solicita acceso al responsable de tu organización." />;
  const [programsR, enrollmentsR, fitnessR, restrictionsR, decisionsR] = await Promise.all([
    db.from("health_surveillance_programs").select("*").eq("organization_id", organizationId).order("name"),
    read || manage ? db.from("health_program_enrollments").select("*").eq("organization_id", organizationId).order("next_review_at") : Promise.resolve({ data: [] }),
    medical ? db.from("occupational_fitness_concepts").select("*").eq("organization_id", organizationId).order("expires_at") : Promise.resolve({ data: [] }),
    medical || hr ? db.from("work_restrictions").select("*").eq("organization_id", organizationId).order("effective_to") : Promise.resolve({ data: [] }),
    medical || hr ? db.from("occupational_health_decisions").select("*").eq("organization_id", organizationId).order("created_at", { ascending: false }) : Promise.resolve({ data: [] }),
  ]);
  const programs = programsR.data ?? [], enrollments = enrollmentsR.data ?? [], fitness = fitnessR.data ?? [], restrictions = restrictionsR.data ?? [], decisions = decisionsR.data ?? [], members = membersR.data ?? [];
  const userIds = members.map((member: any) => member.user_id);
  const { data: profiles } = userIds.length ? await db.from("profiles").select("id,first_name,middle_name,last_name,second_last_name").in("id", userIds) : { data: [] };
  const memberName = (memberId: string) => { const member = members.find((item: any) => item.id === memberId); return displayPersonName(profiles?.find((profile: any) => profile.id === member?.user_id), "Persona con acceso restringido"); };
  const hidden = <input type="hidden" name="organizationId" value={organizationId} />;
  const isExpired = (value: string | null) => Boolean(value && new Date(`${value}T00:00:00Z`).getTime() < new Date().getTime());
  const pendingDecisions = decisions.filter((decision: any) => decision.status === "pending_human_confirmation");

  const programForm = <form action={createHealthProgram} className="grid gap-4">{hidden}<label className="grid gap-1.5 text-sm font-medium">Código<Input name="code" placeholder="PVE-ERGONOMICO" required /></label><label className="grid gap-1.5 text-sm font-medium">Nombre<Input name="name" required /></label><label className="grid gap-1.5 text-sm font-medium">Descripción operativa<Textarea name="description" /></label><Button>Crear programa</Button></form>;

  return <main className="grid gap-7">
    <PageHeader eyebrow="Acceso sensible" title="Salud ocupacional" description="Administra aptitud funcional, restricciones y vigilancia sin almacenar historias clínicas ni diagnósticos." action={manage ? <FormDrawer triggerLabel="Nuevo programa" title="Programa de vigilancia" description="Registra el objetivo operativo y sus revisiones.">{programForm}</FormDrawer> : undefined} />
    <OperationsNav organizationId={organizationId} current="occupational-health" />
    <StatusBanner status={status} />
    <aside className="rounded-[14px] border border-[var(--danger-border)] bg-[var(--danger-soft)] p-4 text-sm leading-6 text-[var(--danger)]"><strong>Datos especialmente protegidos.</strong> Cada perfil ve únicamente la información necesaria para su función. Las decisiones que afectan a una persona exigen confirmación humana independiente.</aside>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Programas activos" value={programs.filter((item: any) => item.status === "active").length} /><KpiCard label="Personas vinculadas" value={enrollments.length} /><KpiCard label="Revisiones vencidas" value={enrollments.filter((item: any) => isExpired(item.next_review_at)).length} /><KpiCard label="Decisiones pendientes" value={pendingDecisions.length} /></section>

    {manage ? <Card><CardHeader><CardTitle>Vincular una persona</CardTitle><p className="text-sm text-[var(--muted)]">La vinculación solo conserva el programa y la próxima revisión.</p></CardHeader><CardContent><FormDrawer triggerLabel="Vincular persona" title="Vinculación a vigilancia" description="No registres información clínica en este formulario." variant="secondary" disabled={!programs.length || !members.length}><form action={enrollHealthProgram} className="grid gap-4">{hidden}<label className="grid gap-1.5 text-sm font-medium">Programa<Select name="health_surveillance_program_id" required>{programs.map((program: any) => <option key={program.id} value={program.id}>{program.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Persona<Select name="organization_member_id" required>{members.map((member: any) => <option key={member.id} value={member.id}>{memberName(member.id)}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Próxima revisión<Input name="next_review_at" type="date" /></label><Button>Vincular al programa</Button></form></FormDrawer></CardContent></Card> : null}

    <section className="grid gap-3"><h2 className="text-lg font-semibold">Programas y vencimientos</h2>{programs.length ? programs.map((program: any) => { const programEnrollments = enrollments.filter((item: any) => item.health_surveillance_program_id === program.id); return <Card key={program.id}><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle>{program.code} · {program.name}</CardTitle><p className="mt-1 text-sm text-[var(--muted)]">{programEnrollments.length} personas vinculadas</p></div><StatusBadge>{program.status}</StatusBadge></div></CardHeader><CardContent>{programEnrollments.length ? <div className="divide-y divide-[var(--border)]">{programEnrollments.map((enrollment: any) => <div key={enrollment.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{memberName(enrollment.organization_member_id)}</p><p className="mt-1 text-xs text-[var(--muted)]">Próxima revisión: {displayDate(enrollment.next_review_at)}</p></div>{isExpired(enrollment.next_review_at) ? <StatusBadge status="danger">overdue</StatusBadge> : <StatusBadge>active</StatusBadge>}</div>)}</div> : <p className="text-sm text-[var(--muted)]">Aún no hay personas vinculadas.</p>}</CardContent></Card>; }) : <EmptyState title="No hay programas" description="Crea un programa para gestionar sus vinculaciones y revisiones." />}</section>

    {medical ? <section className="grid gap-3"><div><h2 className="text-lg font-semibold">Gestión médica autorizada</h2><p className="mt-1 text-sm text-[var(--muted)]">Solo se conservan conceptos funcionales mínimos.</p></div><div className="flex flex-wrap gap-2"><FormDrawer triggerLabel="Registrar aptitud" title="Concepto de aptitud" description="No incluyas diagnóstico, historia clínica ni resultado detallado." variant="secondary"><form action={recordFitness} className="grid gap-4">{hidden}<label className="grid gap-1.5 text-sm font-medium">Persona<Select name="organization_member_id" required>{members.map((member: any) => <option key={member.id} value={member.id}>{memberName(member.id)}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Concepto<Select name="concept"><option value="fit">Apto</option><option value="fit_with_restrictions">Apto con restricciones</option><option value="pending_review">Pendiente de revisión</option><option value="not_issued">No emitido</option></Select></label><label className="grid gap-1.5 text-sm font-medium">Fecha de emisión<Input name="issued_at" type="date" required /></label><label className="grid gap-1.5 text-sm font-medium">Vencimiento<Input name="expires_at" type="date" /></label><Button>Registrar concepto</Button></form></FormDrawer><FormDrawer triggerLabel="Registrar restricción" title="Restricción funcional" description="Describe únicamente la limitación operativa necesaria." variant="secondary" disabled={!fitness.length}><form action={addWorkRestriction} className="grid gap-4">{hidden}<label className="grid gap-1.5 text-sm font-medium">Concepto<Select name="occupational_fitness_concept_id" required>{fitness.map((item: any) => <option key={item.id} value={item.id}>{memberName(item.organization_member_id)} · {conceptLabels[item.concept] ?? "Concepto funcional"}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Restricción<Textarea name="restriction_summary" required /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Desde<Input name="effective_from" type="date" required /></label><label className="grid gap-1.5 text-sm font-medium">Hasta<Input name="effective_to" type="date" /></label></div><Button>Registrar restricción</Button></form></FormDrawer></div></section> : null}

    {hr ? <section className="grid gap-3"><h2 className="text-lg font-semibold">Decisiones con intervención humana</h2><Card><CardContent className="grid gap-4 pt-5"><FormDrawer triggerLabel="Proponer decisión" title="Nueva decisión laboral" description="Registra el motivo funcional. Otra persona autorizada deberá confirmarla." variant="secondary"><form action={createHealthDecision} className="grid gap-4">{hidden}<label className="grid gap-1.5 text-sm font-medium">Persona<Select name="organization_member_id" required>{members.map((member: any) => <option key={member.id} value={member.id}>{memberName(member.id)}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Tipo<Select name="decision_type"><option value="accommodation">Adecuación</option><option value="work_assignment_review">Revisión de asignación</option><option value="restriction_acknowledgement">Reconocimiento de restricción</option></Select></label><label className="grid gap-1.5 text-sm font-medium">Motivo funcional<Textarea name="reason_summary" required /></label><Button>Enviar a confirmación</Button></form></FormDrawer>{pendingDecisions.length ? pendingDecisions.map((decision: any) => <article key={decision.id} className="flex flex-wrap items-center justify-between gap-3 rounded-[10px] border border-[var(--border)] p-3"><div><p className="text-sm font-medium">{decisionLabels[decision.decision_type] ?? "Decisión laboral"}</p><p className="mt-1 text-xs text-[var(--muted)]">{memberName(decision.organization_member_id)}</p></div>{confirm ? <form action={resolveHealthDecision} className="flex gap-2">{hidden}<input type="hidden" name="id" value={decision.id} /><Select name="status"><option value="confirmed">Confirmar</option><option value="cancelled">Cancelar</option></Select><Button size="sm">Registrar decisión</Button></form> : <StatusBadge>pending_review</StatusBadge>}</article>) : <p className="text-sm text-[var(--muted)]">No hay decisiones pendientes de confirmación.</p>}</CardContent></Card></section> : null}

    {medical ? <section className="grid gap-3"><h2 className="text-lg font-semibold">Conceptos y restricciones autorizados</h2>{fitness.length ? <div className="grid gap-3 lg:grid-cols-2">{fitness.map((item: any) => <Card key={item.id}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>{memberName(item.organization_member_id)}</CardTitle><StatusBadge>{isExpired(item.expires_at) ? "overdue" : item.concept}</StatusBadge></div></CardHeader><CardContent><p className="text-sm text-[var(--muted)]">{conceptLabels[item.concept] ?? "Concepto funcional"} · emitido {displayDate(item.issued_at)} · vence {displayDate(item.expires_at)}</p>{restrictions.filter((restriction: any) => restriction.occupational_fitness_concept_id === item.id).map((restriction: any) => <div key={restriction.id} className="mt-3 rounded-[10px] bg-[var(--muted-surface)] p-3 text-sm"><p>{restriction.restriction_summary}</p><p className="mt-1 text-xs text-[var(--muted)]">{displayDate(restriction.effective_from)} a {displayDate(restriction.effective_to)} · <StatusBadge>{restriction.status}</StatusBadge></p></div>)}</CardContent></Card>)}</div> : <EmptyState title="Sin conceptos visibles" description="No hay información funcional autorizada para este perfil." />}</section> : null}
    {hr && !medical ? <section className="grid gap-3"><div><h2 className="text-lg font-semibold">Restricciones funcionales</h2><p className="mt-1 text-sm text-[var(--muted)]">Talento humano consulta únicamente la instrucción operativa necesaria, sin acceder al concepto médico de origen.</p></div>{restrictions.length ? <div className="grid gap-3 lg:grid-cols-2">{restrictions.map((restriction: any) => <Card key={restriction.id}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>Indicación laboral protegida</CardTitle><StatusBadge>{restriction.status}</StatusBadge></div></CardHeader><CardContent><p className="text-sm leading-6">{restriction.restriction_summary}</p><p className="mt-2 text-xs text-[var(--muted)]">Vigente de {displayDate(restriction.effective_from)} a {displayDate(restriction.effective_to)}</p></CardContent></Card>)}</div> : <EmptyState title="Sin restricciones visibles" description="No hay indicaciones laborales autorizadas para este perfil." />}</section> : null}
  </main>;
}
