import { EmptyState } from "@/components/empty-state";
import { FormDrawer } from "@/components/form-drawer";
import { PageHeader } from "@/components/page-header";
import { StatusBanner } from "@/components/status-banner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { KpiCard } from "@/components/ui/kpi-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { createClient } from "@/lib/supabase/server";
import { can } from "@/modules/auth/permissions";
import { verifyRiskControl } from "@/modules/organizations/core-actions";
import { createRiskActivity, createRiskControl, createRiskIdentification, createRiskProcess, createRiskTask } from "@/modules/organizations/risk-actions";
import { RiskAssessmentForm } from "@/modules/organizations/risk-assessment-form";
import { requireTenant } from "@/modules/organizations/tenant";

const hierarchy = [
  ["ELIMINATION", "Eliminación", "Elimina el peligro en su origen."],
  ["SUBSTITUTION", "Sustitución", "Reemplaza el peligro por una alternativa más segura."],
  ["ENGINEERING", "Ingeniería", "Aísla a las personas mediante diseño o barreras técnicas."],
  ["ADMINISTRATIVE", "Administrativo", "Organiza el trabajo, procedimientos y competencias."],
  ["PPE", "EPP", "Última barrera de protección personal."],
] as const;

function asDate(value: string | null) {
  return value ? new Date(`${value}T00:00:00`).toLocaleDateString("es-CO") : "Sin fecha";
}

export default async function RisksPage({ params, searchParams }: { params: Promise<{ organizationId: string }>; searchParams: Promise<{ status?: string }> }) {
  const { organizationId } = await params;
  await requireTenant(organizationId);
  const [mayRead, mayManage, mayValidate, supabase] = await Promise.all([can(organizationId, "risks.read"), can(organizationId, "risks.manage"), can(organizationId, "risks.validate"), createClient()]);
  if (!mayRead) return <EmptyState title="Sin permiso para ver riesgos" description="Solicita acceso de lectura de riesgos a un administrador." />;

  const [{ data: controls }, { data: alerts }, { data: processes }, { data: activities }, { data: riskTasks }, { data: hazards }, { data: identifications }, { data: methodologies }, { data: assessments }, { data: variables }, { data: catalogs }, { data: members }, { data: planningTasks }, { data: improvementActions }, { data: evidenceVersions }] = await Promise.all([
    supabase.from("risk_controls").select("id,control_type,description,status,effectiveness,target_date,next_verification_at,last_verified_at,responsible_user_id,task_id,improvement_action_id,evidence_document_version_id").eq("organization_id", organizationId).order("target_date", { ascending: true, nullsFirst: false }),
    supabase.from("risk_control_alerts").select("id,risk_control_id,alert_type,detected_at").eq("organization_id", organizationId).is("resolved_at", null).order("detected_at", { ascending: false }),
    supabase.from("processes").select("id,name,code").eq("organization_id", organizationId).eq("status", "active"),
    supabase.from("activities").select("id,name,process_id").eq("organization_id", organizationId).eq("status", "active"),
    supabase.from("risk_tasks").select("id,name,activity_id").eq("organization_id", organizationId).eq("status", "active"),
    supabase.from("hazard_catalog").select("id,name,category").eq("status", "active").eq("expert_review_status", "reviewed"),
    supabase.from("risk_identifications").select("id,description,risk_task_id").eq("organization_id", organizationId).eq("status", "active"),
    supabase.from("risk_methodology_versions").select("id,version_code,status,expert_review_status").eq("status","approved").eq("expert_review_status","reviewed"),
    supabase.from("risk_assessments").select("id,risk_identification_id,status,risk_level,created_at").eq("organization_id",organizationId).order("created_at",{ascending:false}),
    supabase.from("risk_methodology_variables").select("methodology_version_id,code,label,data_type,required,definition").order("display_order"),
    supabase.from("risk_methodology_catalogs").select("methodology_version_id,code,entries"),
    supabase.from("organization_members").select("user_id").eq("organization_id", organizationId).eq("status", "active"),
    supabase.from("tasks").select("id,title").eq("organization_id", organizationId).not("status", "in", "(completed,cancelled)").limit(100),
    supabase.from("improvement_actions").select("id,title").eq("organization_id", organizationId).not("status", "in", "(verified,cancelled)").limit(100),
    supabase.from("document_versions").select("id,original_name").eq("organization_id", organizationId).limit(100),
  ]);
  const memberIds = (members ?? []).map((member) => member.user_id);
  const { data: profiles } = memberIds.length ? await supabase.from("profiles").select("id,first_name,last_name").in("id", memberIds) : { data: [] };
  const people = memberIds.map((id) => { const profile = profiles?.find((item) => item.id === id); return { id, name: [profile?.first_name, profile?.last_name].filter(Boolean).join(" ") || "Persona sin nombre" }; });
  const methodologyOptions = (methodologies ?? []).map((methodology) => ({ ...methodology, variables: (variables ?? []).filter((item) => item.methodology_version_id === methodology.id).map((item) => ({ code: item.code, label: item.label, data_type: item.data_type, required: item.required, definition: item.definition })), catalogs: (catalogs ?? []).filter((item) => item.methodology_version_id === methodology.id).map((item) => ({ code: item.code, entries: item.entries })) }));
  const identificationOptions = (identifications ?? []).map((item) => ({ id: item.id, label: item.description }));
  const assessmentOptions = (assessments ?? []).map((item) => ({ id: item.id, label: `Reevaluación del ${new Date(item.created_at).toLocaleDateString("es-CO")}` }));
  const openAlerts = alerts ?? [];
  const controlAlerts = new Map(openAlerts.map((alert) => [alert.risk_control_id, alert.alert_type]));
  const { status } = await searchParams;

  return <div className="grid gap-7"><PageHeader eyebrow="Matriz de peligros" title="Controles y seguimiento" description="La jerarquía orienta la priorización; la decisión y verificación siguen siendo responsabilidad profesional." /><StatusBanner status={status} />
    <div className="grid gap-3 sm:grid-cols-3"><KpiCard label="Controles registrados" value={controls?.length ?? 0} /><KpiCard label="Alertas abiertas" value={openAlerts.length} /><KpiCard label="Verificados" value={controls?.filter((control) => control.last_verified_at).length ?? 0} /></div>
    <Card><CardHeader><h2 className="font-semibold">Jerarquía de controles</h2></CardHeader><CardContent><ol className="grid gap-2 lg:grid-cols-5">{hierarchy.map(([code, label, description], index) => <li key={code} className="rounded-lg border border-[var(--border)] p-3"><p className="text-xs font-bold text-[var(--brand)]">{index + 1}. {label}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{description}</p></li>)}</ol></CardContent></Card>
    {mayManage ? <Card><CardHeader><h2 className="font-semibold">Construir la matriz</h2><p className="mt-1 text-sm text-[var(--muted)]">Avanza en orden. Cada registro conserva el contexto del paso anterior.</p></CardHeader><CardContent className="flex flex-wrap gap-2">
      <FormDrawer triggerLabel="Proceso" title="Nuevo proceso" description="Define el proceso que agrupa las actividades de trabajo." variant="secondary"><form action={createRiskProcess} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1.5 text-sm font-medium">Nombre<Input name="name" required /></label><label className="grid gap-1.5 text-sm font-medium">Código<Input name="code" required /></label><label className="grid gap-1.5 text-sm font-medium">Descripción<Textarea name="description" /></label><Button>Crear proceso</Button></form></FormDrawer>
      <FormDrawer triggerLabel="Actividad" title="Nueva actividad" description="Asocia una actividad con el proceso donde se realiza." variant="secondary"><form action={createRiskActivity} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1.5 text-sm font-medium">Proceso<Select name="process_id" required>{processes?.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Nombre<Input name="name" required /></label><label className="grid gap-1.5 text-sm font-medium">Descripción<Textarea name="description" /></label><Button disabled={!processes?.length}>Crear actividad</Button></form></FormDrawer>
      <FormDrawer triggerLabel="Tarea" title="Nueva tarea de riesgo" description="Describe el trabajo, el lugar y si forma parte de la operación habitual." variant="secondary"><form action={createRiskTask} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1.5 text-sm font-medium">Actividad<Select name="activity_id" required>{activities?.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Nombre<Input name="name" required /></label><label className="grid gap-1.5 text-sm font-medium">Zona o lugar<Input name="zone_or_location" required /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="is_routine" value="true" />Es una tarea rutinaria</label><label className="grid gap-1.5 text-sm font-medium">Descripción<Textarea name="description" /></label><Button disabled={!activities?.length}>Crear tarea</Button></form></FormDrawer>
      <FormDrawer triggerLabel="Peligro" title="Identificar peligro" description="Registra el peligro y sus efectos sin adelantar conclusiones profesionales." variant="secondary"><form action={createRiskIdentification} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1.5 text-sm font-medium">Tarea<Select name="risk_task_id" required>{riskTasks?.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Peligro<Select name="hazard_id" required>{hazards?.map((item)=><option key={item.id} value={item.id}>{item.category} · {item.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Descripción<Textarea name="description" required /></label><label className="grid gap-1.5 text-sm font-medium">Efectos posibles<Textarea name="possible_effects" /></label><label className="grid gap-1.5 text-sm font-medium">Personas expuestas<Input name="exposed_count" type="number" min="0" /></label><label className="grid gap-1.5 text-sm font-medium">Peor consecuencia<Textarea name="worst_consequence" /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="legal_requirement" value="true" />Existe un requisito legal relacionado</label><Button disabled={!riskTasks?.length || !hazards?.length}>Guardar identificación</Button></form></FormDrawer>
      <FormDrawer triggerLabel="Control" title="Nuevo control" description="Prioriza la jerarquía y vincula responsable, seguimiento y evidencia." variant="secondary"><form action={createRiskControl} className="grid gap-4"><input type="hidden" name="organizationId" value={organizationId}/><label className="grid gap-1.5 text-sm font-medium">Peligro identificado<Select name="risk_identification_id" required>{identifications?.map((item)=><option key={item.id} value={item.id}>{item.description}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Tipo de control<Select name="control_type">{hierarchy.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Descripción<Textarea name="description" required /></label><label className="grid gap-1.5 text-sm font-medium">Responsable<Select name="responsible_user_id" defaultValue=""><option value="">Sin asignar</option>{people.map((person)=><option key={person.id} value={person.id}>{person.name}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Fecha objetivo<Input name="target_date" type="date" /></label><label className="grid gap-1.5 text-sm font-medium">Tarea de seguimiento<Select name="task_id" defaultValue=""><option value="">Sin tarea</option>{planningTasks?.map((task)=><option key={task.id} value={task.id}>{task.title}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Acción de mejora<Select name="improvement_action_id" defaultValue=""><option value="">Sin acción</option>{improvementActions?.map((action)=><option key={action.id} value={action.id}>{action.title}</option>)}</Select></label><label className="grid gap-1.5 text-sm font-medium">Evidencia disponible<Select name="evidence_document_version_id" defaultValue=""><option value="">Sin evidencia</option>{evidenceVersions?.map((version)=><option key={version.id} value={version.id}>{version.original_name}</option>)}</Select></label><Button disabled={!identifications?.length}>Agregar control</Button></form></FormDrawer>
    </CardContent></Card> : null}
    {mayManage ? <Card><CardHeader><h2 className="font-semibold">Evaluación y reevaluación</h2></CardHeader><CardContent>{methodologyOptions.length ? <RiskAssessmentForm organizationId={organizationId} identifications={identificationOptions} versions={methodologyOptions} previousAssessments={assessmentOptions} /> : <div className="rounded-[10px] border border-[var(--warning)] bg-[var(--warning-soft)] p-4 text-sm leading-6 text-[var(--warning)]">No hay una metodología aprobada y revisada. El cálculo permanecerá bloqueado hasta que un experto publique una versión válida.</div>}</CardContent></Card> : null}
    {mayValidate && controls?.length ? <Card><CardHeader><h2 className="font-semibold">Registrar verificación</h2></CardHeader><CardContent><form action={verifyRiskControl} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="organizationId" value={organizationId} /><label className="grid gap-1 text-sm font-medium sm:col-span-2">Control<select name="risk_control_id" required className="min-h-10 rounded-md border border-[var(--border)] bg-white px-3 text-sm">{controls.map((control) => <option key={control.id} value={control.id}>{control.description}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Eficacia<select name="effectiveness" defaultValue="effective" className="min-h-10 rounded-md border border-[var(--border)] bg-white px-3 text-sm"><option value="effective">Eficaz</option><option value="partially_effective">Parcialmente eficaz</option><option value="ineffective">Ineficaz</option></select></label><label className="grid gap-1 text-sm font-medium">Próxima verificación<Input name="next_verification_at" type="date" /></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Conclusión<textarea name="verification_note" required minLength={3} className="min-h-24 rounded-md border border-[var(--border)] px-3 py-2 text-sm" /></label><div className="sm:col-span-2"><Button type="submit">Guardar verificación</Button></div></form></CardContent></Card> : null}
    <Card><CardHeader><h2 className="font-semibold">Seguimiento de controles</h2></CardHeader><CardContent className="grid gap-3">{controls?.length ? hierarchy.map(([type, label]) => {
      const entries = controls.filter((control) => control.control_type === type);
      if (!entries.length) return null;
      return <section key={type} className="grid gap-2"><h3 className="text-sm font-semibold">{label}</h3>{entries.map((control) => {
        const alert = controlAlerts.get(control.id);
        return <article key={control.id} className="rounded-lg border border-[var(--border)] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{control.description}</strong><div className="flex gap-2">{alert ? <StatusBadge status="danger">{alert === "overdue" ? "Vencido" : "Ineficaz"}</StatusBadge> : null}<StatusBadge status={control.effectiveness === "effective" ? "active" : control.effectiveness === "ineffective" ? "danger" : "pending"}>{control.effectiveness ?? "Pendiente de verificar"}</StatusBadge></div></div><p className="mt-1 text-xs text-[var(--muted)]">Objetivo: {asDate(control.target_date)} · Próxima verificación: {asDate(control.next_verification_at)} · {control.evidence_document_version_id ? "Evidencia privada vinculada" : "Sin evidencia vinculada"}</p><p className="mt-1 text-xs text-[var(--muted)]">{control.task_id ? "Tarea vinculada" : "Sin tarea"} · {control.improvement_action_id ? "Acción de mejora vinculada" : "Sin acción de mejora"}</p></article>;
      })}</section>;
    }) : <EmptyState title="Sin controles registrados" description="Registra una identificación de riesgo y agrega controles estructurados para iniciar el seguimiento." />}</CardContent></Card></div>;
}
