"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { can, type PermissionCode } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { fitnessSchema, healthDecisionSchema, healthDecisionStateSchema, healthEnrollmentSchema, healthProgramSchema, restrictionSchema } from "./schemas";
const id=z.uuid(); const route=(o:string,s:string)=>`/org/${o}/occupational-health?status=${s}`; const org=(f:FormData)=>id.parse(f.get("organizationId")); const values=(f:FormData)=>Object.fromEntries(f); async function db(){return (await requireAuthenticatedUser()).supabase as any;} async function guard(o:string,p:PermissionCode){if(!(await can(o,p)))redirect(route(o,"forbidden"));} async function finish(o:string,s:string){revalidatePath(`/org/${o}/occupational-health`);redirect(route(o,s));}
export async function createHealthProgram(f:FormData){const o=org(f),x=healthProgramSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"occupational_health.manage");const {error}=await (await db()).from("health_surveillance_programs").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function enrollHealthProgram(f:FormData){const o=org(f),x=healthEnrollmentSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"occupational_health.manage");const {error}=await (await db()).from("health_program_enrollments").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function recordFitness(f:FormData){const o=org(f),x=fitnessSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"occupational_health.medical");const {userId}=await requireAuthenticatedUser();const {error}=await (await db()).from("occupational_fitness_concepts").insert({organization_id:o,...x.data,issued_by_user_id:userId});await finish(o,error?"error":"saved");}
export async function addWorkRestriction(f:FormData){const o=org(f),x=restrictionSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"occupational_health.medical");const {error}=await (await db()).from("work_restrictions").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function createHealthDecision(f:FormData){const o=org(f),x=healthDecisionSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"occupational_health.hr_sensitive");const {error}=await (await db()).from("occupational_health_decisions").insert({organization_id:o,...x.data});await finish(o,error?"error":"saved");}
export async function resolveHealthDecision(f:FormData){const o=org(f),x=healthDecisionStateSchema.safeParse(values(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,x.data.status==="confirmed"?"occupational_health.confirm":"occupational_health.hr_sensitive");const {error}=await (await db()).from("occupational_health_decisions").update({status:x.data.status}).eq("organization_id",o).eq("id",x.data.id);await finish(o,error?"confirmation-error":"saved");}
