-- ETAPA 15: reusable annual planning and task engine. All due instants are UTC timestamptz.
create table public.annual_plans (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,year integer not null check(year between 2000 and 2200),name text not null check(btrim(name)<>''),status text not null default 'draft' check(status in ('draft','active','approved','archived')),budget numeric(14,2) check(budget is null or budget>=0),approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,year));
create table public.plan_activities (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,annual_plan_id uuid not null references public.annual_plans(id) on delete restrict,title text not null check(btrim(title)<>''),description text,priority text not null default 'medium' check(priority in ('critical','high','medium','low')),responsible_user_id uuid references auth.users(id) on delete set null,budget numeric(14,2) check(budget is null or budget>=0),starts_at timestamptz,ends_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or starts_at is null or ends_at>=starts_at));
create table public.task_recurrence_rules (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,frequency text not null check(frequency in ('daily','weekly','monthly','yearly')),interval_count integer not null default 1 check(interval_count between 1 and 365),starts_at timestamptz not null,ends_at timestamptz,timezone text not null default 'America/Bogota',created_at timestamptz not null default now(),check(ends_at is null or ends_at>=starts_at));
create table public.tasks (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,annual_plan_id uuid references public.annual_plans(id) on delete restrict,plan_activity_id uuid references public.plan_activities(id) on delete restrict,improvement_action_id uuid references public.improvement_actions(id) on delete restrict,title text not null check(btrim(title)<>''),description text,priority text not null default 'medium' check(priority in ('critical','high','medium','low')),status text not null default 'todo' check(status in ('todo','in_progress','blocked','completed','cancelled')),assigned_to uuid references auth.users(id) on delete set null,due_at timestamptz,completed_at timestamptz,completed_by uuid references auth.users(id) on delete set null,recurrence_rule_id uuid references public.task_recurrence_rules(id) on delete restrict,occurrence_at timestamptz,occurrence_key text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((recurrence_rule_id is null and occurrence_at is null and occurrence_key is null) or (recurrence_rule_id is not null and occurrence_at is not null and occurrence_key is not null)),unique(organization_id,occurrence_key));
create table public.task_dependencies (task_id uuid not null references public.tasks(id) on delete cascade,depends_on_task_id uuid not null references public.tasks(id) on delete restrict,organization_id uuid not null references public.organizations(id) on delete restrict,created_at timestamptz not null default now(),primary key(task_id,depends_on_task_id),check(task_id<>depends_on_task_id));
create table public.task_comments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,task_id uuid not null references public.tasks(id) on delete cascade,body text not null check(btrim(body)<>''),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table public.task_evidences (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,task_id uuid not null references public.tasks(id) on delete cascade,document_version_id uuid not null references public.document_versions(id) on delete restrict,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(task_id,document_version_id));
create index tasks_org_board_idx on public.tasks(organization_id,status,priority,due_at); create index tasks_assignee_due_idx on public.tasks(organization_id,assigned_to,due_at); create index task_dependencies_org_idx on public.task_dependencies(organization_id,depends_on_task_id);
insert into public.permissions(code,module,action,description) values ('planning.read','planning','read','Consultar plan anual y tareas.'),('planning.manage','planning','manage','Gestionar planes, actividades y tareas.'),('tasks.update_status','tasks','update_status','Actualizar estado de tareas asignadas.'),('tasks.approve','tasks','approve','Aprobar plan anual y cierre de tareas.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code in ('planning.read','planning.manage','tasks.update_status','tasks.approve') where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_task_links() returns trigger language plpgsql security definer set search_path='' as $$ declare org_id uuid; begin
 if tg_table_name='tasks' then if new.plan_activity_id is not null then select organization_id into org_id from public.plan_activities where id=new.plan_activity_id; elsif new.improvement_action_id is not null then select organization_id into org_id from public.improvement_actions where id=new.improvement_action_id; end if; if org_id is not null and org_id<>new.organization_id then raise exception 'task source belongs to another organization' using errcode='23514'; end if;
 elsif tg_table_name='task_dependencies' then select organization_id into org_id from public.tasks where id=new.task_id; if org_id is null or org_id<>new.organization_id or not exists(select 1 from public.tasks where id=new.depends_on_task_id and organization_id=new.organization_id) then raise exception 'task dependency belongs to another organization' using errcode='23514'; end if;
 elsif tg_table_name='task_evidences' then if not exists(select 1 from public.tasks where id=new.task_id and organization_id=new.organization_id) or not exists(select 1 from public.document_versions where id=new.document_version_id and organization_id=new.organization_id) then raise exception 'task evidence belongs to another organization' using errcode='23514'; end if; end if; return new; end; $$;
create or replace function private.validate_task_transition() returns trigger language plpgsql security definer set search_path='' as $$ begin
 if new.status='completed' and old.status<>'completed' then if not private.has_permission(new.organization_id,'tasks.approve') and new.assigned_to is distinct from (select auth.uid()) then raise exception 'only the assignee or an approver can complete the task' using errcode='42501'; end if; if exists(select 1 from public.task_dependencies d join public.tasks blocker on blocker.id=d.depends_on_task_id where d.task_id=new.id and blocker.status<>'completed') then raise exception 'task dependencies are not complete' using errcode='23514'; end if; new.completed_at:=now(); new.completed_by:=(select auth.uid()); end if; return new; end; $$;
create or replace function private.generate_recurring_tasks(p_until timestamptz) returns integer language plpgsql security definer set search_path='' as $$ declare r record; n integer:=0; inserted integer; slot timestamptz; begin for r in select * from public.task_recurrence_rules where starts_at<=p_until and (ends_at is null or ends_at>=starts_at) loop slot:=r.starts_at; while slot<=p_until and (r.ends_at is null or slot<=r.ends_at) loop insert into public.tasks(organization_id,title,priority,recurrence_rule_id,occurrence_at,occurrence_key,created_by,due_at) values(r.organization_id,'Tarea recurrente','medium',r.id,slot,r.id||':'||to_char(slot at time zone 'UTC','YYYYMMDDHH24MISS'),(select auth.uid()),slot) on conflict(organization_id,occurrence_key) do nothing; get diagnostics inserted = row_count; n:=n+inserted; slot:=case r.frequency when 'daily' then slot+(r.interval_count||' days')::interval when 'weekly' then slot+(r.interval_count||' weeks')::interval when 'monthly' then slot+(r.interval_count||' months')::interval else slot+(r.interval_count||' years')::interval end; end loop; end loop; return n; end; $$;
revoke all on function private.validate_task_links(),private.validate_task_transition(),private.generate_recurring_tasks(timestamptz) from public,anon,authenticated,service_role;
alter table public.annual_plans enable row level security; alter table public.plan_activities enable row level security; alter table public.task_recurrence_rules enable row level security; alter table public.tasks enable row level security; alter table public.task_dependencies enable row level security; alter table public.task_comments enable row level security; alter table public.task_evidences enable row level security;
grant select,insert,update on public.annual_plans,public.plan_activities,public.task_recurrence_rules,public.tasks,public.task_dependencies,public.task_comments,public.task_evidences to authenticated;
create policy annual_plans_read on public.annual_plans for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy annual_plans_write on public.annual_plans for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage')));
create policy plan_activities_read on public.plan_activities for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy plan_activities_write on public.plan_activities for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage')));
create policy tasks_read on public.tasks for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy tasks_write on public.tasks for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage')));
create policy task_related_read on public.task_dependencies for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy task_related_write on public.task_dependencies for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage'))); create policy task_comments_read on public.task_comments for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy task_comments_write on public.task_comments for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage'))); create policy task_evidences_read on public.task_evidences for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy task_evidences_write on public.task_evidences for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage'))); create policy recurrence_read on public.task_recurrence_rules for select to authenticated using((select private.has_permission(organization_id,'planning.read'))); create policy recurrence_write on public.task_recurrence_rules for all to authenticated using((select private.has_permission(organization_id,'planning.manage'))) with check((select private.has_permission(organization_id,'planning.manage')));
create trigger tasks_validate_links before insert or update on public.tasks for each row execute function private.validate_task_links(); create trigger task_dependencies_validate_links before insert or update on public.task_dependencies for each row execute function private.validate_task_links(); create trigger task_evidences_validate_links before insert or update on public.task_evidences for each row execute function private.validate_task_links(); create trigger tasks_transition before update on public.tasks for each row execute function private.validate_task_transition(); create trigger tasks_updated before update on public.tasks for each row execute function private.set_updated_at(); create trigger tasks_audit after insert or update on public.tasks for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
