-- ETAPA 31: authorized retrieval ledger. This schema deliberately contains no autonomous action executor.
create table public.copilot_conversations (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,actor_user_id uuid not null references auth.users(id) on delete restrict,title text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.copilot_messages (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,conversation_id uuid not null references public.copilot_conversations(id) on delete restrict,actor_user_id uuid references auth.users(id) on delete set null,role text not null check(role in ('user','assistant','system')),content text not null check(length(content)<=8000),prompt_injection_flag boolean not null default false,created_at timestamptz not null default now());
create table public.copilot_sources (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,assistant_message_id uuid not null references public.copilot_messages(id) on delete restrict,source_type text not null check(source_type in ('document_version','normative_source_version','requirement','assessment','risk','other')),source_id uuid not null,source_version_id uuid,excerpt text check(excerpt is null or length(excerpt)<=1000),created_at timestamptz not null default now());
create table public.copilot_action_proposals (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,conversation_id uuid not null references public.copilot_conversations(id) on delete restrict,proposal_type text not null check(proposal_type in ('draft_task','draft_action','draft_document','critical_classification','critical_approval','legal_or_medical')),proposal jsonb not null check(jsonb_typeof(proposal)='object'),status text not null default 'pending_human_confirmation' check(status in ('pending_human_confirmation','accepted','rejected','expired')),proposed_by uuid references auth.users(id) on delete set null,reviewed_by uuid references auth.users(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now());
create index copilot_conversations_org_actor_idx on public.copilot_conversations(organization_id,actor_user_id,created_at desc); create index copilot_messages_conversation_idx on public.copilot_messages(conversation_id,created_at); create index copilot_sources_message_idx on public.copilot_sources(assistant_message_id); create index copilot_proposals_org_status_idx on public.copilot_action_proposals(organization_id,status);
insert into public.permissions(code,module,action,description) values ('copilot.read','copilot','read','Usar recuperación autorizada de Copilot.'),('copilot.manage','copilot','manage','Gestionar conversaciones y borradores.'),('copilot.confirm_critical','copilot','confirm_critical','Confirmar propuestas críticas de Copilot.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code like 'copilot.%' where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_copilot_links() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_table_name='copilot_messages' and not exists(select 1 from public.copilot_conversations where id=new.conversation_id and organization_id=new.organization_id) then raise exception 'copilot conversation belongs to another organization' using errcode='23514'; end if; if tg_table_name='copilot_sources' and not exists(select 1 from public.copilot_messages where id=new.assistant_message_id and organization_id=new.organization_id and role='assistant') then raise exception 'copilot source belongs to another organization' using errcode='23514'; end if; if tg_table_name='copilot_action_proposals' and not exists(select 1 from public.copilot_conversations where id=new.conversation_id and organization_id=new.organization_id) then raise exception 'copilot proposal belongs to another organization' using errcode='23514'; end if; return new; end; $$;
create or replace function private.require_copilot_confirmation() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status='accepted' and old.status<>'accepted' then if new.proposal_type in ('critical_classification','critical_approval','legal_or_medical') and not private.has_permission(new.organization_id,'copilot.confirm_critical') then raise exception 'human confirmation permission required' using errcode='42501'; end if; new.reviewed_by:=(select auth.uid()); new.reviewed_at:=now(); end if; return new; end; $$;
revoke all on function private.validate_copilot_links(),private.require_copilot_confirmation() from public,anon,authenticated,service_role;
alter table public.copilot_conversations enable row level security; alter table public.copilot_messages enable row level security; alter table public.copilot_sources enable row level security; alter table public.copilot_action_proposals enable row level security;
grant select,insert,update on public.copilot_conversations,public.copilot_messages,public.copilot_sources,copilot_action_proposals to authenticated;
create policy copilot_conversations_own on public.copilot_conversations for all to authenticated using(actor_user_id=(select auth.uid())) with check(actor_user_id=(select auth.uid()));
create policy copilot_messages_own on public.copilot_messages for select to authenticated using(exists(select 1 from public.copilot_conversations c where c.id=conversation_id and c.actor_user_id=(select auth.uid()))); create policy copilot_messages_insert on public.copilot_messages for insert to authenticated with check(exists(select 1 from public.copilot_conversations c where c.id=conversation_id and c.actor_user_id=(select auth.uid())));
create policy copilot_sources_own on public.copilot_sources for select to authenticated using(exists(select 1 from public.copilot_messages m join public.copilot_conversations c on c.id=m.conversation_id where m.id=assistant_message_id and c.actor_user_id=(select auth.uid())));
create policy copilot_proposals_read on public.copilot_action_proposals for select to authenticated using(exists(select 1 from public.copilot_conversations c where c.id=conversation_id and c.actor_user_id=(select auth.uid()))); create policy copilot_proposals_write on public.copilot_action_proposals for all to authenticated using((select private.has_permission(organization_id,'copilot.manage'))) with check((select private.has_permission(organization_id,'copilot.manage')));
create trigger copilot_messages_links before insert on public.copilot_messages for each row execute function private.validate_copilot_links(); create trigger copilot_sources_links before insert on public.copilot_sources for each row execute function private.validate_copilot_links(); create trigger copilot_proposals_links before insert or update on public.copilot_action_proposals for each row execute function private.validate_copilot_links(); create trigger copilot_proposals_confirm before update on public.copilot_action_proposals for each row execute function private.require_copilot_confirmation(); create trigger copilot_proposals_audit after insert or update on public.copilot_action_proposals for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
