-- ETAPA 32: internal integration registry and replay-safe staging imports. No external connectors are enabled.
create table public.integration_connections (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,provider_code text not null,display_name text not null,status text not null default 'draft' check(status in ('draft','disabled','active','error')),config jsonb not null default '{}'::jsonb check(jsonb_typeof(config)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,provider_code));
create table public.import_jobs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,import_type text not null check(import_type in ('workforce_csv','workforce_xlsx','structure_csv','structure_xlsx')),file_name text not null,content_hash text not null,mode text not null default 'preview' check(mode in ('preview','commit','rolled_back')),status text not null default 'uploaded' check(status in ('uploaded','validating','preview_ready','committing','completed','failed','rolled_back')),idempotency_key uuid not null unique,mapping jsonb not null default '{}'::jsonb check(jsonb_typeof(mapping)='object'),summary jsonb not null default '{}'::jsonb check(jsonb_typeof(summary)='object'),created_by uuid references auth.users(id) on delete set null,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,import_type,content_hash));
create table public.import_rows (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,import_job_id uuid not null references public.import_jobs(id) on delete restrict,row_number integer not null check(row_number>0),raw_data jsonb not null check(jsonb_typeof(raw_data)='object'),normalized_data jsonb check(normalized_data is null or jsonb_typeof(normalized_data)='object'),validation_errors jsonb not null default '[]'::jsonb check(jsonb_typeof(validation_errors)='array'),status text not null default 'pending' check(status in ('pending','valid','invalid','imported','rolled_back')),target_reference text,created_at timestamptz not null default now(),unique(import_job_id,row_number));
create table public.import_job_effects (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,import_job_id uuid not null references public.import_jobs(id) on delete restrict,entity_type text not null check(entity_type in ('organization_member','legal_entity','site','area')),entity_id uuid not null,operation text not null check(operation in ('insert','update')),before_data jsonb,created_at timestamptz not null default now(),unique(import_job_id,entity_type,entity_id));
create index import_jobs_org_status_idx on public.import_jobs(organization_id,status,created_at desc); create index import_rows_job_status_idx on public.import_rows(import_job_id,status); create index import_effects_job_idx on public.import_job_effects(import_job_id);
insert into public.permissions(code,module,action,description) values ('imports.read','imports','read','Consultar importaciones y errores por fila.'),('imports.manage','imports','manage','Cargar, validar y confirmar importaciones.'),('integrations.manage','integrations','manage','Configurar integraciones internas autorizadas.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code like any(array['imports.%','integrations.%']) where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_import_links() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_table_name in ('import_rows','import_job_effects') and not exists(select 1 from public.import_jobs where id=new.import_job_id and organization_id=new.organization_id) then raise exception 'import child belongs to another organization' using errcode='23514'; end if; return new; end; $$;
create or replace function private.complete_import_job(p_import_job_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare j public.import_jobs%rowtype; e uuid; begin select * into j from public.import_jobs where id=p_import_job_id for update; if not found or not private.has_permission(j.organization_id,'imports.manage') then raise exception 'import not authorized' using errcode='42501'; end if; if exists(select 1 from public.import_rows where import_job_id=j.id and status='invalid') then raise exception 'import contains invalid rows' using errcode='23514'; end if; update public.import_jobs set status='completed',mode='commit',completed_at=now(),summary=jsonb_build_object('rows', (select count(*) from public.import_rows where import_job_id=j.id),'imported_rows',(select count(*) from public.import_rows where import_job_id=j.id and status='imported')) where id=j.id; perform private.enqueue_domain_event(j.organization_id,'workforce.import.completed','import_job',j.id,jsonb_build_object('import_job_id',j.id,'type',j.import_type),j.id); return j.id; end; $$;
revoke all on function private.validate_import_links(),private.complete_import_job(uuid) from public,anon,authenticated,service_role;
alter table public.integration_connections enable row level security; alter table public.import_jobs enable row level security; alter table public.import_rows enable row level security; alter table public.import_job_effects enable row level security;
grant select,insert,update on public.integration_connections,public.import_jobs,public.import_rows,public.import_job_effects to authenticated;
create policy integrations_manage on public.integration_connections for all to authenticated using((select private.has_permission(organization_id,'integrations.manage'))) with check((select private.has_permission(organization_id,'integrations.manage')));
create policy import_jobs_read on public.import_jobs for select to authenticated using((select private.has_permission(organization_id,'imports.read'))); create policy import_jobs_write on public.import_jobs for all to authenticated using((select private.has_permission(organization_id,'imports.manage'))) with check((select private.has_permission(organization_id,'imports.manage')));
create policy import_rows_read on public.import_rows for select to authenticated using((select private.has_permission(organization_id,'imports.read'))); create policy import_rows_write on public.import_rows for all to authenticated using((select private.has_permission(organization_id,'imports.manage'))) with check((select private.has_permission(organization_id,'imports.manage')));
create policy import_effects_read on public.import_job_effects for select to authenticated using((select private.has_permission(organization_id,'imports.read'))); create policy import_effects_write on public.import_job_effects for all to authenticated using((select private.has_permission(organization_id,'imports.manage'))) with check((select private.has_permission(organization_id,'imports.manage')));
create trigger import_rows_links before insert or update on public.import_rows for each row execute function private.validate_import_links(); create trigger import_effects_links before insert on public.import_job_effects for each row execute function private.validate_import_links(); create trigger import_jobs_updated before update on public.import_jobs for each row execute function private.set_updated_at(); create trigger import_jobs_audit after insert or update on public.import_jobs for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
