-- ETAPA 34: commercial state is deliberately separate from authorization and tenant data.
create table public.billing_plans (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,status text not null default 'active' check(status in ('draft','active','archived')),limits jsonb not null default '{}'::jsonb check(jsonb_typeof(limits)='object'),feature_flags jsonb not null default '{}'::jsonb check(jsonb_typeof(feature_flags)='object'),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.billing_subscriptions (id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete restrict,billing_plan_id uuid not null references public.billing_plans(id) on delete restrict,status text not null check(status in ('trialing','active','past_due','suspended','cancelled')),trial_ends_at timestamptz,current_period_start timestamptz,current_period_end timestamptz,provider_customer_reference text,provider_subscription_reference text unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.billing_usage_periods (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,billing_subscription_id uuid not null references public.billing_subscriptions(id) on delete restrict,period_start timestamptz not null,period_end timestamptz not null,usage jsonb not null default '{}'::jsonb check(jsonb_typeof(usage)='object'),created_at timestamptz not null default now(),unique(billing_subscription_id,period_start),check(period_end>period_start));
create table public.billing_webhook_events (id uuid primary key default gen_random_uuid(),provider_code text not null,event_reference text not null,payload_hash text not null,signature_valid boolean not null default false,status text not null default 'received' check(status in ('received','processed','failed','discarded')),received_at timestamptz not null default now(),processed_at timestamptz,last_error text,unique(provider_code,event_reference));
create table private.reinova_admin_users (user_id uuid primary key references auth.users(id) on delete restrict,created_at timestamptz not null default now());
create table public.saas_support_sessions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,reinova_admin_user_id uuid not null references auth.users(id) on delete restrict,reason text not null,status text not null default 'requested' check(status in ('requested','active','ended','rejected')),started_at timestamptz,ended_at timestamptz,created_at timestamptz not null default now());
create index billing_usage_org_period_idx on public.billing_usage_periods(organization_id,period_start desc); create index support_sessions_org_status_idx on public.saas_support_sessions(organization_id,status);
insert into public.permissions(code,module,action,description) values ('billing.read','billing','read','Consultar estado comercial del tenant.'),('billing.manage','billing','manage','Administrar suscripción y límites del tenant.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code like 'billing.%' where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_billing_links() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_table_name='billing_usage_periods' and not exists(select 1 from public.billing_subscriptions where id=new.billing_subscription_id and organization_id=new.organization_id) then raise exception 'billing period belongs to another organization' using errcode='23514'; end if; if tg_table_name='saas_support_sessions' and not exists(select 1 from private.reinova_admin_users where user_id=new.reinova_admin_user_id) then raise exception 'support user is not a Reinova administrator' using errcode='42501'; end if; return new; end; $$;
revoke all on function private.validate_billing_links() from public,anon,authenticated,service_role;
alter table public.billing_plans enable row level security; alter table public.billing_subscriptions enable row level security; alter table public.billing_usage_periods enable row level security; alter table public.billing_webhook_events enable row level security; alter table public.saas_support_sessions enable row level security;
grant select on public.billing_plans to authenticated; grant select,insert,update on public.billing_subscriptions,public.billing_usage_periods,public.saas_support_sessions to authenticated;
create policy billing_plans_read on public.billing_plans for select to authenticated using((select auth.uid()) is not null);
create policy billing_subscriptions_read on public.billing_subscriptions for select to authenticated using((select private.has_permission(organization_id,'billing.read'))); create policy billing_subscriptions_write on public.billing_subscriptions for all to authenticated using((select private.has_permission(organization_id,'billing.manage'))) with check((select private.has_permission(organization_id,'billing.manage')));
create policy billing_usage_read on public.billing_usage_periods for select to authenticated using((select private.has_permission(organization_id,'billing.read')));
create policy support_sessions_read on public.saas_support_sessions for select to authenticated using((select private.has_permission(organization_id,'billing.read')));
create trigger billing_usage_links before insert on public.billing_usage_periods for each row execute function private.validate_billing_links(); create trigger support_session_links before insert or update on public.saas_support_sessions for each row execute function private.validate_billing_links(); create trigger billing_subscriptions_audit after insert or update on public.billing_subscriptions for each row execute function private.capture_core_audit(); create trigger saas_support_sessions_audit after insert or update on public.saas_support_sessions for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
