-- ETAPA 16: technical risk methodologies are versioned configuration, not law or hardcoded logic.
create table public.risk_methodologies (
 id uuid primary key default gen_random_uuid(), code text not null unique check(code ~ '^[A-Z][A-Z0-9_]{2,80}$'), name text not null check(length(btrim(name)) between 3 and 200), description text, normative_source_version_id uuid references public.normative_source_versions(id) on delete restrict, status text not null default 'draft' check(status in ('draft','active','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.risk_methodology_versions (
 id uuid primary key default gen_random_uuid(), methodology_id uuid not null references public.risk_methodologies(id) on delete restrict, version_code text not null check(length(btrim(version_code)) between 1 and 80), effective_from date, effective_to date, status text not null default 'draft' check(status in ('draft','reviewed','approved','retired')), expert_review_status text not null default 'pending' check(expert_review_status in ('pending','reviewed','rejected')), interpretive_note text not null check(length(btrim(interpretive_note)) between 3 and 2000), configuration jsonb not null default '{}'::jsonb check(jsonb_typeof(configuration)='object'), supersedes_version_id uuid references public.risk_methodology_versions(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(methodology_id,version_code), check(effective_to is null or effective_from is null or effective_to>=effective_from), check(status<>'approved' or expert_review_status='reviewed')
);
create table public.risk_methodology_variables (id uuid primary key default gen_random_uuid(), methodology_version_id uuid not null references public.risk_methodology_versions(id) on delete cascade, code text not null check(code ~ '^[A-Z][A-Z0-9_]{1,80}$'), label text not null check(btrim(label)<>''), data_type text not null check(data_type in ('number','text','boolean','select','multiselect')), required boolean not null default false, definition jsonb not null default '{}'::jsonb check(jsonb_typeof(definition)='object'), display_order integer not null default 0 check(display_order>=0), unique(methodology_version_id,code));
create table public.risk_methodology_catalogs (id uuid primary key default gen_random_uuid(), methodology_version_id uuid not null references public.risk_methodology_versions(id) on delete cascade, code text not null check(code ~ '^[A-Z][A-Z0-9_]{1,80}$'), label text not null check(btrim(label)<>''), entries jsonb not null default '[]'::jsonb check(jsonb_typeof(entries)='array'), unique(methodology_version_id,code));
create table public.risk_methodology_formulas (id uuid primary key default gen_random_uuid(), methodology_version_id uuid not null references public.risk_methodology_versions(id) on delete cascade, code text not null check(code ~ '^[A-Z][A-Z0-9_]{1,80}$'), expression text not null check(btrim(expression)<>''), output_variable_code text not null, interpretation jsonb not null default '{}'::jsonb check(jsonb_typeof(interpretation)='object'), status text not null default 'draft' check(status in ('draft','reviewed','approved')), expert_review_status text not null default 'pending' check(expert_review_status in ('pending','reviewed','rejected')), unique(methodology_version_id,code), check(status<>'approved' or expert_review_status='reviewed'));
create table public.risk_methodology_interpretation_rules (id uuid primary key default gen_random_uuid(), methodology_version_id uuid not null references public.risk_methodology_versions(id) on delete cascade, rule_code text not null check(rule_code ~ '^[A-Z][A-Z0-9_]{1,80}$'), condition jsonb not null check(jsonb_typeof(condition)='object'), outcome jsonb not null check(jsonb_typeof(outcome)='object'), explanation text not null check(btrim(explanation)<>''), status text not null default 'draft' check(status in ('draft','reviewed','approved')), expert_review_status text not null default 'pending' check(expert_review_status in ('pending','reviewed','rejected')), unique(methodology_version_id,rule_code), check(status<>'approved' or expert_review_status='reviewed'));
create table public.risk_assessments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict, risk_methodology_version_id uuid not null references public.risk_methodology_versions(id) on delete restrict, status text not null default 'draft' check(status in ('draft','in_progress','completed','validated','voided')), input_data jsonb not null default '{}'::jsonb check(jsonb_typeof(input_data)='object'), result_data jsonb not null default '{}'::jsonb check(jsonb_typeof(result_data)='object'), assessed_at timestamptz, assessed_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index risk_methodology_versions_methodology_effective_idx on public.risk_methodology_versions(methodology_id,effective_from desc); create index risk_assessments_org_methodology_idx on public.risk_assessments(organization_id,risk_methodology_version_id,created_at desc);
insert into public.permissions(code,module,action,description) values ('risk_methodologies.read','risk_methodologies','read','Consultar metodologías de riesgo.'),('risk_methodologies.manage','risk_methodologies','manage','Gestionar configuraciones metodológicas.'),('risk_assessments.read','risk_assessments','read','Consultar evaluaciones de riesgo.'),('risk_assessments.manage','risk_assessments','manage','Gestionar evaluaciones de riesgo.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code in ('risk_methodologies.read','risk_assessments.read','risk_assessments.manage') where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
alter table public.risk_methodologies enable row level security; alter table public.risk_methodology_versions enable row level security; alter table public.risk_methodology_variables enable row level security; alter table public.risk_methodology_catalogs enable row level security; alter table public.risk_methodology_formulas enable row level security; alter table public.risk_methodology_interpretation_rules enable row level security; alter table public.risk_assessments enable row level security;
grant select on public.risk_methodologies,public.risk_methodology_versions,public.risk_methodology_variables,public.risk_methodology_catalogs,public.risk_methodology_formulas,public.risk_methodology_interpretation_rules to authenticated; grant select,insert,update on public.risk_assessments to authenticated;
create policy risk_methodologies_read on public.risk_methodologies for select to authenticated using((select auth.uid()) is not null); create policy risk_methodology_versions_read on public.risk_methodology_versions for select to authenticated using((select auth.uid()) is not null); create policy risk_methodology_variables_read on public.risk_methodology_variables for select to authenticated using((select auth.uid()) is not null); create policy risk_methodology_catalogs_read on public.risk_methodology_catalogs for select to authenticated using((select auth.uid()) is not null); create policy risk_methodology_formulas_read on public.risk_methodology_formulas for select to authenticated using((select auth.uid()) is not null); create policy risk_methodology_rules_read on public.risk_methodology_interpretation_rules for select to authenticated using((select auth.uid()) is not null); create policy risk_assessments_read on public.risk_assessments for select to authenticated using((select private.has_permission(organization_id,'risk_assessments.read'))); create policy risk_assessments_write on public.risk_assessments for all to authenticated using((select private.has_permission(organization_id,'risk_assessments.manage'))) with check((select private.has_permission(organization_id,'risk_assessments.manage')));
create trigger risk_methodologies_updated before update on public.risk_methodologies for each row execute function private.set_updated_at(); create trigger risk_methodology_versions_updated before update on public.risk_methodology_versions for each row execute function private.set_updated_at(); create trigger risk_assessments_updated before update on public.risk_assessments for each row execute function private.set_updated_at(); create trigger risk_assessments_audit after insert or update on public.risk_assessments for each row execute function private.capture_core_audit();
insert into public.risk_methodologies(code,name,description,normative_source_version_id,status) select 'GTC45_RISK_ASSESSMENT','Metodología de evaluación de riesgos basada en GTC 45','Referencia técnica configurable; no sustituye la revisión experta ni reproduce el contenido de la guía.',v.id,'draft' from public.normative_source_versions v join public.normative_sources s on s.id=v.source_id where s.code='GTC_45' and v.version_code='GTC45' on conflict(code) do nothing;
insert into public.risk_methodology_versions(methodology_id,version_code,effective_from,status,expert_review_status,interpretive_note,configuration) select m.id,'INITIAL','2012-01-01','draft','pending','Estructura inicial para variables, catálogos, fórmulas e interpretación. Requiere revisión experta antes de aprobar o usar para decisiones.',jsonb_build_object('scope','risk_assessment','legal_interpretation','pending_expert_review') from public.risk_methodologies m where m.code='GTC45_RISK_ASSESSMENT' on conflict(methodology_id,version_code) do nothing;
notify pgrst,'reload schema';
