-- ETAPAS 26-28: governance, audit and analytical history. No user-authored SQL is evaluated.
create table public.committee_types (id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,default_config jsonb not null default '{}'::jsonb check(jsonb_typeof(default_config)='object'),status text not null default 'active' check(status in ('active','archived')),created_at timestamptz not null default now());
insert into public.committee_types(code,name,description) values ('copasst','COPASST','Configuración inicial revisable.'),('coexistence','Comité de Convivencia','Configuración inicial revisable.') on conflict(code) do nothing;
create table public.committees (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,site_id uuid references public.sites(id) on delete restrict,committee_type_id uuid not null references public.committee_types(id) on delete restrict,name text not null,config jsonb not null default '{}'::jsonb check(jsonb_typeof(config)='object'),status text not null default 'active' check(status in ('draft','active','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.committee_periods (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,committee_id uuid not null references public.committees(id) on delete restrict,starts_on date not null,ends_on date,status text not null default 'active' check(status in ('planned','active','closed')),created_at timestamptz not null default now(),check(ends_on is null or ends_on>=starts_on),unique(committee_id,starts_on));
create table public.committee_members (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,committee_period_id uuid not null references public.committee_periods(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,internal_role text not null check(internal_role in ('chair','secretary','principal','alternate','advisor')),status text not null default 'active' check(status in ('active','inactive')),appointed_on date not null default current_date,created_at timestamptz not null default now(),unique(committee_period_id,organization_member_id));
create table public.meeting_templates (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,title text not null,version_number integer not null check(version_number>0),body jsonb not null default '{}'::jsonb check(jsonb_typeof(body)='object'),status text not null default 'draft' check(status in ('draft','approved','archived')),approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),unique(organization_id,code,version_number));
create table public.committee_meetings (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,committee_period_id uuid not null references public.committee_periods(id) on delete restrict,meeting_template_id uuid references public.meeting_templates(id) on delete restrict,scheduled_at timestamptz not null,held_at timestamptz,status text not null default 'scheduled' check(status in ('scheduled','held','cancelled','approved')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.meeting_agenda_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,committee_meeting_id uuid not null references public.committee_meetings(id) on delete restrict,position integer not null check(position>0),title text not null,notes text,unique(committee_meeting_id,position));
create table public.meeting_attendance (committee_meeting_id uuid not null references public.committee_meetings(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,organization_id uuid not null references public.organizations(id) on delete restrict,present boolean not null default false,attendance_note text,primary key(committee_meeting_id,organization_member_id));
create table public.meeting_minutes (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,committee_meeting_id uuid not null unique references public.committee_meetings(id) on delete restrict,content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'),status text not null default 'draft' check(status in ('draft','approved','void')),approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,document_version_id uuid references public.document_versions(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.committee_commitments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,meeting_minutes_id uuid not null references public.meeting_minutes(id) on delete restrict,task_id uuid references public.tasks(id) on delete set null,title text not null,due_at timestamptz,status text not null default 'open' check(status in ('open','in_progress','completed','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.audit_programs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,name text not null,year integer not null check(year between 2000 and 2200),scope_summary text,criteria jsonb not null default '[]'::jsonb check(jsonb_typeof(criteria)='array'),status text not null default 'draft' check(status in ('draft','active','closed','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,year,name));
create table public.audit_engagements (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_program_id uuid not null references public.audit_programs(id) on delete restrict,site_id uuid references public.sites(id) on delete restrict,title text not null,scope_summary text,criteria jsonb not null default '[]'::jsonb check(jsonb_typeof(criteria)='array'),require_independent_approval boolean not null default true,status text not null default 'planned' check(status in ('planned','in_progress','reported','closed','cancelled')),scheduled_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.audit_team_members (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null references public.audit_engagements(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,team_role text not null check(team_role in ('lead_auditor','auditor','technical_expert','observer')),independence_declared_at timestamptz,created_at timestamptz not null default now(),unique(audit_engagement_id,organization_member_id));
create table public.audit_agenda_items (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null references public.audit_engagements(id) on delete restrict,scheduled_at timestamptz,title text not null,assigned_to uuid references auth.users(id) on delete set null,status text not null default 'planned' check(status in ('planned','completed','cancelled')));
create table public.audit_checklists (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null references public.audit_engagements(id) on delete restrict,code text not null,title text not null,criteria_reference text,response text check(response in ('conforming','nonconforming','observation','not_applicable')),notes text,unique(audit_engagement_id,code));
create table public.audit_evidences (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null references public.audit_engagements(id) on delete restrict,document_version_id uuid not null references public.document_versions(id) on delete restrict,created_at timestamptz not null default now(),unique(audit_engagement_id,document_version_id));
create table public.audit_findings (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null references public.audit_engagements(id) on delete restrict,classification text not null check(classification in ('nonconformity','observation','opportunity')),title text not null,description text,criteria_reference text,status text not null default 'open' check(status in ('open','action_planned','verified','closed','dismissed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.audit_reports (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_engagement_id uuid not null unique references public.audit_engagements(id) on delete restrict,summary text not null,status text not null default 'draft' check(status in ('draft','issued','approved','void')),document_version_id uuid references public.document_versions(id) on delete restrict,approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table public.audit_actions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,audit_finding_id uuid not null references public.audit_findings(id) on delete restrict,improvement_action_id uuid references public.improvement_actions(id) on delete set null,task_id uuid references public.tasks(id) on delete set null,title text not null,status text not null default 'open' check(status in ('open','in_progress','verified','closed','cancelled')),due_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.management_reviews (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,period_start date not null,period_end date not null,status text not null default 'draft' check(status in ('draft','in_review','approved','void')),chair_user_id uuid references auth.users(id) on delete set null,approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(period_end>=period_start),unique(organization_id,period_start,period_end));
create table public.management_review_entries (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,management_review_id uuid not null references public.management_reviews(id) on delete restrict,entry_type text not null check(entry_type in ('audit','indicator','compliance','risk','incident','resource','change','other')),content jsonb not null default '{}'::jsonb check(jsonb_typeof(content)='object'));
create table public.management_review_decisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,management_review_id uuid not null references public.management_reviews(id) on delete restrict,decision text not null,created_at timestamptz not null default now());
create table public.management_review_commitments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,management_review_id uuid not null references public.management_reviews(id) on delete restrict,task_id uuid references public.tasks(id) on delete set null,title text not null,due_at timestamptz,status text not null default 'open' check(status in ('open','in_progress','completed','cancelled')),created_at timestamptz not null default now());

create table public.indicator_catalog (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,name text not null,description text,owner_user_id uuid references auth.users(id) on delete set null,status text not null default 'active' check(status in ('draft','active','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table public.indicator_versions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,indicator_id uuid not null references public.indicator_catalog(id) on delete restrict,version_number integer not null check(version_number>0),formula_description text not null,source_config jsonb not null default '{}'::jsonb check(jsonb_typeof(source_config)='object'),periodicity text not null check(periodicity in ('daily','weekly','monthly','quarterly','yearly')),target_value numeric,target_direction text not null default 'at_least' check(target_direction in ('at_least','at_most','exact')),dimensions jsonb not null default '[]'::jsonb check(jsonb_typeof(dimensions)='array'),status text not null default 'draft' check(status in ('draft','approved','archived')),approved_at timestamptz,approved_by uuid references auth.users(id) on delete set null,effective_from date not null default current_date,effective_to date,created_at timestamptz not null default now(),check(effective_to is null or effective_to>=effective_from),unique(indicator_id,version_number));
create table public.indicator_calculation_runs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,indicator_version_id uuid not null references public.indicator_versions(id) on delete restrict,period_start date not null,period_end date not null,idempotency_key uuid not null unique,status text not null default 'completed' check(status in ('pending','running','completed','failed')),calculated_at timestamptz not null default now(),created_at timestamptz not null default now(),check(period_end>=period_start));
create table public.indicator_results (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,indicator_version_id uuid not null references public.indicator_versions(id) on delete restrict,calculation_run_id uuid not null references public.indicator_calculation_runs(id) on delete restrict,period_start date not null,period_end date not null,dimension_values jsonb not null default '{}'::jsonb check(jsonb_typeof(dimension_values)='object'),value numeric not null,target_value numeric,explanation jsonb not null default '{}'::jsonb check(jsonb_typeof(explanation)='object'),created_at timestamptz not null default now(),unique(calculation_run_id,dimension_values));
create view public.management_dashboard_metrics with (security_invoker=true) as select o.id organization_id,(select count(*) from public.tasks t where t.organization_id=o.id and t.status not in ('completed','cancelled')) open_tasks,(select count(*) from public.improvement_actions a where a.organization_id=o.id and a.status not in ('verified','cancelled')) open_actions,(select count(*) from public.documents d where d.organization_id=o.id and d.status='active') active_documents from public.organizations o;

create index committee_periods_committee_idx on public.committee_periods(committee_id,status); create index committee_members_period_idx on public.committee_members(committee_period_id); create index committee_meetings_period_idx on public.committee_meetings(committee_period_id,scheduled_at); create index audit_engagements_program_idx on public.audit_engagements(audit_program_id,status); create index audit_team_engagement_idx on public.audit_team_members(audit_engagement_id); create index audit_findings_engagement_idx on public.audit_findings(audit_engagement_id,status); create index audit_actions_finding_idx on public.audit_actions(audit_finding_id,status); create index management_reviews_org_period_idx on public.management_reviews(organization_id,period_start desc); create index indicator_versions_indicator_idx on public.indicator_versions(indicator_id,status); create index indicator_results_org_period_idx on public.indicator_results(organization_id,period_start,period_end);
insert into public.permissions(code,module,action,description) values ('committees.read','committees','read','Consultar comités y reuniones.'),('committees.manage','committees','manage','Gestionar comités, actas y compromisos.'),('committees.approve','committees','approve','Aprobar actas y plantillas.'),('audits.read','audits','read','Consultar auditorías y revisión por la dirección.'),('audits.manage','audits','manage','Gestionar programas, evidencias y hallazgos.'),('audits.approve','audits','approve','Aprobar informes y cierres.'),('analytics.read','analytics','read','Consultar indicadores y dashboard.'),('analytics.manage','analytics','manage','Gestionar catálogo y resultados de indicadores.'),('analytics.approve','analytics','approve','Aprobar versiones de indicadores.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code like any(array['committees.%','audits.%','analytics.%']) where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_governance_links() returns trigger language plpgsql security definer set search_path='' as $$ declare x uuid; begin
 if tg_table_name='committee_periods' then select organization_id into x from public.committees where id=new.committee_id;
 elsif tg_table_name='committee_members' then select organization_id into x from public.committee_periods where id=new.committee_period_id;
 elsif tg_table_name='committee_meetings' then select organization_id into x from public.committee_periods where id=new.committee_period_id;
 elsif tg_table_name='meeting_minutes' then select organization_id into x from public.committee_meetings where id=new.committee_meeting_id;
 elsif tg_table_name='committee_commitments' then select organization_id into x from public.meeting_minutes where id=new.meeting_minutes_id;
 elsif tg_table_name='audit_engagements' then select organization_id into x from public.audit_programs where id=new.audit_program_id;
 elsif tg_table_name in ('audit_team_members','audit_agenda_items','audit_checklists','audit_evidences','audit_findings','audit_reports') then select organization_id into x from public.audit_engagements where id=new.audit_engagement_id;
 elsif tg_table_name='audit_actions' then select organization_id into x from public.audit_findings where id=new.audit_finding_id;
 elsif tg_table_name in ('management_review_entries','management_review_decisions','management_review_commitments') then select organization_id into x from public.management_reviews where id=new.management_review_id;
 elsif tg_table_name='indicator_versions' then select organization_id into x from public.indicator_catalog where id=new.indicator_id;
 elsif tg_table_name in ('indicator_calculation_runs','indicator_results') then select organization_id into x from public.indicator_versions where id=new.indicator_version_id;
 else return new; end if;
 if x is null or x<>new.organization_id then raise exception 'related record belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='committee_commitments' and new.task_id is not null and not exists(select 1 from public.tasks where id=new.task_id and organization_id=new.organization_id) then raise exception 'committee commitment task belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='audit_evidences' and not exists(select 1 from public.document_versions where id=new.document_version_id and organization_id=new.organization_id) then raise exception 'audit evidence belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='audit_actions' and ((new.task_id is not null and not exists(select 1 from public.tasks where id=new.task_id and organization_id=new.organization_id)) or (new.improvement_action_id is not null and not exists(select 1 from public.improvement_actions where id=new.improvement_action_id and organization_id=new.organization_id))) then raise exception 'audit action link belongs to another organization' using errcode='23514'; end if;
 return new; end; $$;
create or replace function private.lock_governance_approvals() returns trigger language plpgsql security definer set search_path='' as $$ begin
 if tg_table_name='meeting_minutes' and old.status='approved' and row(new.*) is distinct from row(old.*) then raise exception 'approved meeting minutes are immutable' using errcode='55000'; end if;
 if tg_table_name='meeting_minutes' and new.status='approved' and old.status<>'approved' then if not private.has_permission(new.organization_id,'committees.approve') then raise exception 'committee approval permission required' using errcode='42501'; end if; new.approved_at:=now(); new.approved_by:=(select auth.uid()); end if;
 if tg_table_name='audit_reports' and new.status='approved' and old.status<>'approved' then if not private.has_permission(new.organization_id,'audits.approve') then raise exception 'audit approval permission required' using errcode='42501'; end if; if exists(select 1 from public.audit_team_members tm join public.audit_engagements e on e.id=tm.audit_engagement_id join public.organization_members om on om.id=tm.organization_member_id where e.id=new.audit_engagement_id and e.require_independent_approval and om.user_id=(select auth.uid())) then raise exception 'auditor cannot approve own audit report' using errcode='42501'; end if; new.approved_at:=now(); new.approved_by:=(select auth.uid()); end if; return new; end; $$;
revoke all on function private.validate_governance_links(),private.lock_governance_approvals() from public,anon,authenticated,service_role;
alter table public.committee_types enable row level security;
grant select on public.committee_types to authenticated;
create policy committee_types_read on public.committee_types for select to authenticated using ((select auth.uid()) is not null);
do $$ declare pair text[]; t text; p text; begin foreach pair slice 1 in array array[['committees','committees.read'],['committee_periods','committees.read'],['committee_members','committees.read'],['meeting_templates','committees.read'],['committee_meetings','committees.read'],['meeting_agenda_items','committees.read'],['meeting_attendance','committees.read'],['meeting_minutes','committees.read'],['committee_commitments','committees.read'],['audit_programs','audits.read'],['audit_engagements','audits.read'],['audit_team_members','audits.read'],['audit_agenda_items','audits.read'],['audit_checklists','audits.read'],['audit_evidences','audits.read'],['audit_findings','audits.read'],['audit_reports','audits.read'],['audit_actions','audits.read'],['management_reviews','audits.read'],['management_review_entries','audits.read'],['management_review_decisions','audits.read'],['management_review_commitments','audits.read'],['indicator_catalog','analytics.read'],['indicator_versions','analytics.read'],['indicator_calculation_runs','analytics.read'],['indicator_results','analytics.read']] loop t:=pair[1]; p:=pair[2]; execute format('alter table public.%I enable row level security; grant select,insert,update on public.%I to authenticated; create policy %I on public.%I for select to authenticated using ((select private.has_permission(organization_id,%L))); create policy %I on public.%I for all to authenticated using ((select private.has_permission(organization_id,%L))) with check ((select private.has_permission(organization_id,%L)))',t,t,t||'_read',t,p,t||'_write',t,replace(p,'.read','.manage'),replace(p,'.read','.manage')); end loop; end $$;
grant select on public.management_dashboard_metrics to authenticated;
create trigger committee_period_links before insert or update on public.committee_periods for each row execute function private.validate_governance_links(); create trigger committee_member_links before insert or update on public.committee_members for each row execute function private.validate_governance_links(); create trigger committee_meeting_links before insert or update on public.committee_meetings for each row execute function private.validate_governance_links(); create trigger minutes_links before insert or update on public.meeting_minutes for each row execute function private.validate_governance_links(); create trigger commitments_links before insert or update on public.committee_commitments for each row execute function private.validate_governance_links(); create trigger audit_engagement_links before insert or update on public.audit_engagements for each row execute function private.validate_governance_links(); create trigger audit_team_links before insert or update on public.audit_team_members for each row execute function private.validate_governance_links(); create trigger audit_finding_links before insert or update on public.audit_findings for each row execute function private.validate_governance_links(); create trigger audit_report_links before insert or update on public.audit_reports for each row execute function private.validate_governance_links(); create trigger audit_action_links before insert or update on public.audit_actions for each row execute function private.validate_governance_links(); create trigger indicator_version_links before insert or update on public.indicator_versions for each row execute function private.validate_governance_links(); create trigger indicator_run_links before insert or update on public.indicator_calculation_runs for each row execute function private.validate_governance_links(); create trigger indicator_result_links before insert or update on public.indicator_results for each row execute function private.validate_governance_links(); create trigger minutes_lock before update on public.meeting_minutes for each row execute function private.lock_governance_approvals(); create trigger audit_report_approval before update on public.audit_reports for each row execute function private.lock_governance_approvals();
create trigger committee_minutes_audit after insert or update on public.meeting_minutes for each row execute function private.capture_core_audit(); create trigger audit_reports_audit after insert or update on public.audit_reports for each row execute function private.capture_core_audit(); create trigger audit_findings_audit after insert or update on public.audit_findings for each row execute function private.capture_core_audit(); create trigger indicator_results_audit after insert on public.indicator_results for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
