-- ETAPA 24: minimum occupational-health administration. Explicitly excludes medical records and diagnoses.
create table public.health_surveillance_programs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,code text not null,name text not null check(btrim(name)<>''),description text,status text not null default 'active' check(status in ('draft','active','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table public.occupational_fitness_concepts (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,concept text not null check(concept in ('fit','fit_with_restrictions','pending_review','not_issued')),issued_at date not null,expires_at date,issued_by_user_id uuid references auth.users(id) on delete set null,evidence_document_version_id uuid references public.document_versions(id) on delete restrict,created_at timestamptz not null default now(),check(expires_at is null or expires_at>=issued_at));
create table public.work_restrictions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,occupational_fitness_concept_id uuid not null references public.occupational_fitness_concepts(id) on delete restrict,restriction_summary text not null check(btrim(restriction_summary)<>''),effective_from date not null,effective_to date,status text not null default 'active' check(status in ('active','expired','revoked')),created_at timestamptz not null default now(),check(effective_to is null or effective_to>=effective_from));
create table public.health_program_enrollments (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,health_surveillance_program_id uuid not null references public.health_surveillance_programs(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,status text not null default 'active' check(status in ('active','completed','withdrawn')),next_review_at date,created_at timestamptz not null default now(),unique(health_surveillance_program_id,organization_member_id));
create table public.occupational_health_decisions (id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,organization_member_id uuid not null references public.organization_members(id) on delete restrict,decision_type text not null check(decision_type in ('accommodation','work_assignment_review','restriction_acknowledgement')),reason_summary text not null check(btrim(reason_summary)<>''),status text not null default 'pending_human_confirmation' check(status in ('pending_human_confirmation','confirmed','cancelled')),confirmed_at timestamptz,confirmed_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create index fitness_concepts_org_member_expiry_idx on public.occupational_fitness_concepts(organization_id,organization_member_id,expires_at); create index work_restrictions_concept_idx on public.work_restrictions(occupational_fitness_concept_id,status); create index health_enrollments_org_review_idx on public.health_program_enrollments(organization_id,next_review_at);
insert into public.permissions(code,module,action,description) values ('occupational_health.read','occupational_health','read','Consultar estados operativos de salud ocupacional.'),('occupational_health.manage','occupational_health','manage','Gestionar programas y vencimientos.'),('occupational_health.hr_sensitive','occupational_health','hr_sensitive','Consultar restricciones funcionales para gestión humana.'),('occupational_health.medical','occupational_health','medical','Registrar conceptos ocupacionales autorizados.'),('occupational_health.confirm','occupational_health','confirm','Confirmar decisiones humanas que afectan a una persona.') on conflict(code) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.code in ('occupational_health.read','occupational_health.manage','occupational_health.hr_sensitive','occupational_health.medical','occupational_health.confirm') where r.code='organization_admin' and r.organization_id is null on conflict do nothing;
create or replace function private.validate_occupational_health_links() returns trigger language plpgsql security definer set search_path='' as $$ begin
 if tg_table_name='occupational_fitness_concepts' and (not exists(select 1 from public.organization_members where id=new.organization_member_id and organization_id=new.organization_id) or (new.evidence_document_version_id is not null and not exists(select 1 from public.document_versions where id=new.evidence_document_version_id and organization_id=new.organization_id))) then raise exception 'occupational health concept belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='work_restrictions' and not exists(select 1 from public.occupational_fitness_concepts where id=new.occupational_fitness_concept_id and organization_id=new.organization_id) then raise exception 'restriction belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='health_program_enrollments' and (not exists(select 1 from public.health_surveillance_programs where id=new.health_surveillance_program_id and organization_id=new.organization_id) or not exists(select 1 from public.organization_members where id=new.organization_member_id and organization_id=new.organization_id)) then raise exception 'health program enrollment belongs to another organization' using errcode='23514'; end if;
 if tg_table_name='occupational_health_decisions' and not exists(select 1 from public.organization_members where id=new.organization_member_id and organization_id=new.organization_id) then raise exception 'health decision belongs to another organization' using errcode='23514'; end if; return new; end; $$;
create or replace function private.require_human_health_confirmation() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status='confirmed' and old.status<>'confirmed' then if not private.has_permission(new.organization_id,'occupational_health.confirm') then raise exception 'human confirmation permission required' using errcode='42501'; end if; new.confirmed_at:=now(); new.confirmed_by:=(select auth.uid()); end if; return new; end; $$;
revoke all on function private.validate_occupational_health_links(),private.require_human_health_confirmation() from public,anon,authenticated,service_role;
alter table public.health_surveillance_programs enable row level security; alter table public.occupational_fitness_concepts enable row level security; alter table public.work_restrictions enable row level security; alter table public.health_program_enrollments enable row level security; alter table public.occupational_health_decisions enable row level security;
grant select,insert,update on public.health_surveillance_programs,public.health_program_enrollments,public.occupational_health_decisions to authenticated; grant select,insert on public.occupational_fitness_concepts,public.work_restrictions to authenticated;
create policy health_programs_read on public.health_surveillance_programs for select to authenticated using((select private.has_permission(organization_id,'occupational_health.read'))); create policy health_programs_write on public.health_surveillance_programs for all to authenticated using((select private.has_permission(organization_id,'occupational_health.manage'))) with check((select private.has_permission(organization_id,'occupational_health.manage')));
create policy fitness_concepts_read on public.occupational_fitness_concepts for select to authenticated using((select private.has_permission(organization_id,'occupational_health.medical')) or (select private.has_permission(organization_id,'occupational_health.read'))); create policy fitness_concepts_insert on public.occupational_fitness_concepts for insert to authenticated with check((select private.has_permission(organization_id,'occupational_health.medical')));
create policy restrictions_read on public.work_restrictions for select to authenticated using((select private.has_permission(organization_id,'occupational_health.medical')) or (select private.has_permission(organization_id,'occupational_health.hr_sensitive'))); create policy restrictions_insert on public.work_restrictions for insert to authenticated with check((select private.has_permission(organization_id,'occupational_health.medical')));
create policy health_enrollments_read on public.health_program_enrollments for select to authenticated using((select private.has_permission(organization_id,'occupational_health.read'))); create policy health_enrollments_write on public.health_program_enrollments for all to authenticated using((select private.has_permission(organization_id,'occupational_health.manage'))) with check((select private.has_permission(organization_id,'occupational_health.manage')));
create policy health_decisions_read on public.occupational_health_decisions for select to authenticated using((select private.has_permission(organization_id,'occupational_health.hr_sensitive')) or (select private.has_permission(organization_id,'occupational_health.medical'))); create policy health_decisions_write on public.occupational_health_decisions for all to authenticated using((select private.has_permission(organization_id,'occupational_health.hr_sensitive'))) with check((select private.has_permission(organization_id,'occupational_health.hr_sensitive')));
create trigger fitness_links before insert on public.occupational_fitness_concepts for each row execute function private.validate_occupational_health_links(); create trigger restriction_links before insert on public.work_restrictions for each row execute function private.validate_occupational_health_links(); create trigger enrollment_links before insert or update on public.health_program_enrollments for each row execute function private.validate_occupational_health_links(); create trigger decision_links before insert or update on public.occupational_health_decisions for each row execute function private.validate_occupational_health_links(); create trigger decision_confirmation before update on public.occupational_health_decisions for each row execute function private.require_human_health_confirmation();
create trigger fitness_audit after insert on public.occupational_fitness_concepts for each row execute function private.capture_core_audit(); create trigger restriction_audit after insert on public.work_restrictions for each row execute function private.capture_core_audit(); create trigger decision_audit after insert or update on public.occupational_health_decisions for each row execute function private.capture_core_audit(); notify pgrst,'reload schema';
