"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { can } from "@/modules/auth/permissions";
import { createClient } from "@/lib/supabase/server";
import { assessmentCreateSchema, assessmentItemSchema, assessmentMutationSchema, classificationProposalSchema, domainStatus, evaluateApplicabilitySchema, reviewClassificationSchema, snapshotSchema } from "./schemas";

const path = (organizationId: string, status: string, section = "overview") => `/org/${organizationId}/compliance?section=${section}&status=${status}`;
async function guard(organizationId: string, permission: Parameters<typeof can>[1]) { if (!(await can(organizationId, permission))) redirect(path(organizationId, "forbidden")); }
function refresh(organizationId: string) { revalidatePath(`/org/${organizationId}/compliance`); revalidatePath(`/org/${organizationId}`, "layout"); }
type RpcClient = { rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: unknown; error: { message?: string } | null }> };

export async function createClassificationProposal(formData: FormData) {
  const parsed = classificationProposalSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect(path(String(formData.get("organizationId") ?? ""), "error", "classification"));
  await guard(parsed.data.organizationId, "classifications.manage"); const supabase = await createClient();
  const { data: current } = await supabase.from("organization_classifications").select("id,employee_count,risk_class,ciiu_code,economic_activity,standard_profile_id").eq("organization_id", parsed.data.organizationId).is("effective_to", null).maybeSingle();
  const { error } = await supabase.from("classification_change_proposals").insert({ organization_id: parsed.data.organizationId, current_classification_id: current?.id ?? null, proposed_employee_count: parsed.data.employee_count, proposed_risk_class: parsed.data.risk_class, proposed_ciiu_code: parsed.data.ciiu_code ?? null, proposed_economic_activity: parsed.data.economic_activity ?? null, proposed_standard_profile_id: parsed.data.standard_profile_id, evaluator_version_id: parsed.data.evaluator_version_id, proposed_effective_from: parsed.data.proposed_effective_from, comparison: { current: current ?? null, proposed: parsed.data }, reasons: [parsed.data.reason] });
  refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "proposal-created", "classification"));
}

export async function approveClassificationProposal(formData: FormData) { const parsed = reviewClassificationSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "classifications.manage"); const { error } = await (await createClient() as unknown as RpcClient).rpc("approve_classification_change", { p_proposal_id: parsed.data.proposalId }); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "approved", "classification")); }
export async function rejectClassificationProposal(formData: FormData) { const parsed = reviewClassificationSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "classifications.manage"); const { error } = await (await createClient() as unknown as RpcClient).rpc("reject_classification_change", { p_proposal_id: parsed.data.proposalId, p_note: parsed.data.note }); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "rejected", "classification")); }
export async function runApplicabilityEvaluation(formData: FormData) { const parsed = evaluateApplicabilitySchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "applicability.evaluate"); const { error } = await (await createClient() as unknown as RpcClient).rpc("evaluate_organization_applicability", { p_organization_id: parsed.data.organizationId, p_as_of: parsed.data.asOf ?? new Date().toISOString().slice(0, 10) }); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "evaluated", "applicability")); }
export async function createManualSnapshot(formData: FormData) { const parsed = snapshotSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "snapshots.create"); const { error } = await (await createClient() as unknown as RpcClient).rpc("create_organization_standard_snapshot", { p_organization_id: parsed.data.organizationId, p_snapshot_type: "MANUAL_SNAPSHOT", p_reason: parsed.data.reason, p_snapshot_date: parsed.data.snapshotDate ?? new Date().toISOString().slice(0, 10), p_classification_id: null }); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "snapshot-created", "snapshots")); }

export async function createAssessment(formData: FormData) {
  const parsed = assessmentCreateSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "assessments.manage"); const supabase = await createClient();
  const { data: snapshot } = await supabase.from("organization_standard_snapshots").select("organization_id,standard_profile_version_id").eq("organization_id", parsed.data.organizationId).eq("id", parsed.data.snapshotId).maybeSingle();
  if (!snapshot) redirect(path(parsed.data.organizationId, "notfound", "assessments"));
  const { data: rule } = await supabase.from("assessment_scoring_rules").select("id,status,expert_review_status,standard_profile_version_id").eq("id", parsed.data.scoringRuleId).maybeSingle();
  if (!rule || rule.status !== "approved" || rule.expert_review_status !== "reviewed" || rule.standard_profile_version_id !== snapshot.standard_profile_version_id) redirect(path(parsed.data.organizationId, "expert-pending", "assessments"));
  const { data: assessment, error } = await supabase.from("assessments").insert({ organization_id: parsed.data.organizationId, snapshot_id: parsed.data.snapshotId, standard_profile_version_id: snapshot.standard_profile_version_id, scoring_rule_id: rule.id, responsible_user_id: parsed.data.responsibleUserId ?? null, status: "draft" }).select("id").single();
  if (error || !assessment) redirect(path(parsed.data.organizationId, domainStatus(error), "assessments"));
  const { data: items } = await supabase.from("organization_standard_snapshot_items").select("id").eq("snapshot_id", parsed.data.snapshotId);
  const { error: itemError } = items?.length ? await supabase.from("assessment_items").insert(items.map((item) => ({ assessment_id: assessment.id, snapshot_item_id: item.id }))) : { error: null };
  refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, itemError ? domainStatus(itemError) : "assessment-created", "assessments"));
}
export async function updateAssessmentItem(formData: FormData) { const parsed = assessmentItemSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "assessments.manage"); const { error } = await (await createClient()).from("assessment_items").update({ response: parsed.data.response, observation: parsed.data.observation ?? null, justification: parsed.data.justification ?? null, responsible_user_id: parsed.data.responsibleUserId ?? null }).eq("assessment_id", parsed.data.assessmentId).eq("id", parsed.data.itemId); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "saved", "assessments")); }
export async function completeAssessment(formData: FormData) { const parsed = assessmentMutationSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "assessments.manage"); const { error } = await (await createClient() as unknown as RpcClient).rpc("complete_assessment", { p_assessment_id: parsed.data.assessmentId }); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "completed", "assessments")); }
export async function validateAssessment(formData: FormData) { const parsed = assessmentMutationSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) redirect("/organizations"); await guard(parsed.data.organizationId, "assessments.validate"); const { error } = await (await createClient()).from("assessments").update({ status: "validated" }).eq("organization_id", parsed.data.organizationId).eq("id", parsed.data.assessmentId).eq("status", "completed"); refresh(parsed.data.organizationId); redirect(path(parsed.data.organizationId, error ? domainStatus(error) : "validated", "assessments")); }
