"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation"; import {can,type PermissionCode} from "@/modules/auth/permissions"; import {requireAuthenticatedUser} from "@/modules/organizations/tenant"; import {attendanceSchema,catalogSchema,enrollmentSchema,gradeSchema,planSchema,questionSchema,sessionSchema,templateSchema} from "./schemas";
const route=(o:string,s:string)=>`/org/${o}/training?status=${s}`; const oid=(f:FormData)=>String(f.get("organizationId")??""); const client=async()=> (await requireAuthenticatedUser()).supabase as any;
async function guard(o:string,p:PermissionCode){if(!(await can(o,p)))redirect(route(o,"forbidden"));}
async function save(o:string,op:()=>Promise<{error:any}>){const r=await op();revalidatePath(`/org/${o}/training`);redirect(route(o,r.error?"error":"saved"));}
export async function createCatalog(f:FormData){const o=oid(f),x=catalogSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const {userId}=await requireAuthenticatedUser();await save(o,async()=> (await client()).from("training_catalog").insert({organization_id:o,...x.data,created_by:userId}));}
export async function createPlan(f:FormData){const o=oid(f),x=planSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const {userId}=await requireAuthenticatedUser();await save(o,async()=> (await client()).from("training_plans").insert({organization_id:o,year:x.data.year,title:x.data.title,description:x.data.description,created_by:userId,status:"active"}));}
export async function createSession(f:FormData){const o=oid(f),x=sessionSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const {userId}=await requireAuthenticatedUser();await save(o,async()=> (await client()).from("training_sessions").insert({organization_id:o,training_plan_id:x.data.plan_id,training_catalog_id:x.data.catalog_id,title:x.data.title,starts_at:x.data.starts_at,ends_at:x.data.ends_at,capacity:x.data.capacity,created_by:userId}));}
export async function invite(f:FormData){const o=oid(f),x=enrollmentSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const {userId}=await requireAuthenticatedUser();await save(o,async()=> (await client()).from("training_enrollments").insert({organization_id:o,training_session_id:x.data.session_id,organization_member_id:x.data.member_id,created_by:userId}));}
export async function recordAttendance(f:FormData){const o=oid(f),x=attendanceSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.validate");const {userId}=await requireAuthenticatedUser();await save(o,async()=> (await client()).from("training_attendances").insert({organization_id:o,training_enrollment_id:x.data.enrollment_id,status:x.data.status,checked_by:userId}));}
export async function createTemplate(f:FormData){const o=oid(f),x=templateSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const {userId}=await requireAuthenticatedUser();const {error}=await (await client()).from("training_evaluation_templates").insert({organization_id:o,training_catalog_id:x.data.catalog_id,title:x.data.title,passing_percent:x.data.passing_percent,version_number:1,status:"published",created_by:userId});revalidatePath(`/org/${o}/training`);redirect(route(o,error?"error":"saved"));}
export async function addQuestion(f:FormData){const o=oid(f),x=questionSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.manage");const db=await client();const {data,error}=await db.from("training_evaluation_questions").insert({organization_id:o,template_id:x.data.template_id,prompt:x.data.prompt,weight:x.data.weight,display_order:Date.now()%100000}).select("id").single();if(!error&&data)await db.from("training_evaluation_options").insert([{organization_id:o,question_id:data.id,label:x.data.correct_label,is_correct:true,display_order:1},{organization_id:o,question_id:data.id,label:x.data.incorrect_label,is_correct:false,display_order:2}]);revalidatePath(`/org/${o}/training`);redirect(route(o,error?"error":"saved"));}
export async function grade(f:FormData){const o=oid(f),x=gradeSchema.safeParse(Object.fromEntries(f));if(!x.success)redirect(route(o,"invalid"));await guard(o,"training.validate");const {error}=await (await client()).rpc("grade_training_evaluation",{p_enrollment_id:x.data.enrollment_id,p_template_id:x.data.template_id,p_answers:x.data.answers});revalidatePath(`/org/${o}/training`);redirect(route(o,error?"error":"graded"));}
