/* eslint-disable @typescript-eslint/no-explicit-any */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/empty-state";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { can } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { addQuestion, createCatalog, createPlan, createSession, createTemplate, grade, invite, recordAttendance } from "@/modules/training/actions";

export default async function TrainingPage({ params }: { params: Promise<{ organizationId: string }> }) {
  const { organizationId } = await params;
  const { supabase } = await requireAuthenticatedUser(); const db = supabase as any;
  const [read, manage, validate] = await Promise.all([can(organizationId, "training.read"), can(organizationId, "training.manage"), can(organizationId, "training.validate")]);
  if (!read) return <EmptyState title="Sin permiso" description="Solicita acceso a capacitaciones." />;
  const [catalog, plans, sessions, members, enrollments, templates, evaluations, certificates, indicators] = await Promise.all([
    db.from("training_catalog").select("*").eq("organization_id", organizationId), db.from("training_plans").select("*").eq("organization_id", organizationId), db.from("training_sessions").select("*").eq("organization_id", organizationId), db.from("organization_members").select("id,user_id").eq("organization_id", organizationId).eq("status", "active"), db.from("training_enrollments").select("*").eq("organization_id", organizationId), db.from("training_evaluation_templates").select("*").eq("organization_id", organizationId), db.from("training_evaluations").select("*").eq("organization_id", organizationId), db.from("training_certificates").select("*").eq("organization_id", organizationId), db.from("training_plan_indicators").select("*").eq("organization_id", organizationId),
  ]);
  const hidden = <input type="hidden" name="organizationId" value={organizationId} />;
  return <main className="grid gap-5 p-6"><header><h1 className="text-3xl font-semibold">Capacitaciones y competencias</h1><p className="text-sm text-[var(--muted)]">Convocatoria, evidencia privada, evaluación objetiva y certificados trazables.</p></header>
    {manage ? <section className="grid gap-3 lg:grid-cols-3"><Card><CardHeader>Catálogo</CardHeader><CardContent><form action={createCatalog} className="grid gap-2">{hidden}<Input name="code" placeholder="INDUCCION_SST" required /><Input name="title" placeholder="Capacitación" required /><Input name="duration_minutes" type="number" placeholder="Minutos" /><Input name="validity_days" type="number" placeholder="Vigencia días" /><Button>Crear</Button></form></CardContent></Card><Card><CardHeader>Plan</CardHeader><CardContent><form action={createPlan} className="grid gap-2">{hidden}<Input name="year" type="number" defaultValue={new Date().getUTCFullYear()} /><Input name="title" placeholder="Plan anual" required /><select name="training_catalog_id">{catalog.data?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Button>Crear</Button></form></CardContent></Card><Card><CardHeader>Sesión</CardHeader><CardContent><form action={createSession} className="grid gap-2">{hidden}<select name="plan_id">{plans.data?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><select name="catalog_id">{catalog.data?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Input name="title" placeholder="Sesión" required /><Input name="starts_at" type="datetime-local" required /><Input name="ends_at" type="datetime-local" required /><Button>Programar</Button></form></CardContent></Card></section> : null}
    <section className="grid gap-3"><h2 className="text-xl font-semibold">Sesiones y convocatorias</h2>{sessions.data?.length ? sessions.data.map((session:any)=><Card key={session.id}><CardHeader>{session.title}</CardHeader><CardContent className="grid gap-2">{manage?<form action={invite} className="flex gap-2">{hidden}<input type="hidden" name="session_id" value={session.id}/><select name="member_id">{members.data?.map((m:any)=><option key={m.id} value={m.id}>{m.user_id}</option>)}</select><Button size="sm">Convocar</Button></form>:null}{enrollments.data?.filter((e:any)=>e.training_session_id===session.id).map((e:any)=><form key={e.id} action={recordAttendance} className="flex gap-2 text-sm">{hidden}<input type="hidden" name="enrollment_id" value={e.id}/><span>{e.organization_member_id} · {e.status}</span>{validate?<><select name="status"><option value="present">Presente</option><option value="absent">Ausente</option><option value="excused">Excusado</option></select><Button size="sm">Registrar</Button></>:null}</form>)}</CardContent></Card>) : <EmptyState title="Sin sesiones" description="Crea un catálogo, plan y sesión." />}</section>
    {manage?<section className="grid gap-3 lg:grid-cols-2"><Card><CardHeader>Plantilla</CardHeader><CardContent><form action={createTemplate} className="grid gap-2">{hidden}<select name="catalog_id">{catalog.data?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Input name="title" placeholder="Evaluación" required /><Input name="passing_percent" type="number" defaultValue="70" min="0" max="100"/><Button>Publicar</Button></form></CardContent></Card><Card><CardHeader>Pregunta</CardHeader><CardContent><form action={addQuestion} className="grid gap-2">{hidden}<select name="template_id">{templates.data?.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><Textarea name="prompt" placeholder="Pregunta" required/><Input name="weight" type="number" defaultValue="1" min="0.01" step="0.01"/><Input name="correct_label" placeholder="Opción correcta" required/><Input name="incorrect_label" placeholder="Opción incorrecta" required/><Button>Agregar</Button></form></CardContent></Card></section>:null}
    {validate?<section className="grid gap-3"><h2 className="text-xl font-semibold">Evaluar y certificar</h2>{enrollments.data?.map((e:any)=><form key={e.id} action={grade} className="grid gap-2 rounded border p-3">{hidden}<input type="hidden" name="enrollment_id" value={e.id}/><select name="template_id">{templates.data?.map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select><Textarea name="answers" placeholder={'[{"question_id":"...","option_id":"..."}]'} required/><Button>Calcular y certificar si aprueba</Button></form>)}</section>:null}
    <section className="grid gap-2"><h2 className="text-xl font-semibold">Indicadores y certificados</h2>{indicators.data?.map((i:any)=><p key={i.training_plan_id}>Cobertura {i.coverage_percent??"—"}% · eficacia {i.effectiveness_percent??"—"}%</p>)}{evaluations.data?.map((e:any)=><p key={e.id}>Resultado {e.score}% · {e.passed?"Aprobada":"No aprobada"}</p>)}{certificates.data?.map((c:any)=><p key={c.id}>{c.certificate_code} · vence {c.expires_at??"Sin vencimiento"}</p>)}</section>
  </main>;
}
