"use server";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { can, type PermissionCode } from "@/modules/auth/permissions";
import { requireAuthenticatedUser } from "@/modules/organizations/tenant";
import { agendaSchema, attendanceSchema, auditActionSchema, auditAgendaSchema, auditChecklistSchema, auditEngagementSchema, auditEvidenceSchema, auditFindingSchema, auditProgramSchema, auditReportSchema, auditTeamSchema, committeeMemberSchema, committeeSchema, commitmentSchema, managementCommitmentSchema, managementDecisionSchema, managementEntrySchema, managementReviewSchema, meetingSchema, minutesSchema, periodSchema, statusSchema } from "./schemas";

const uuid = z.uuid();
const path = (organizationId: string, status: string) => `/org/${organizationId}/governance?status=${status}`;
const organization = (formData: FormData) => uuid.parse(formData.get("organizationId"));
const values = (formData: FormData) => Object.fromEntries(formData);
const iso = (value: string | null) => value ? new Date(value).toISOString() : null;
async function client() { return (await requireAuthenticatedUser()).supabase as any; }
async function guard(organizationId: string, permission: PermissionCode, siteId?: string | null) { if (!(await can(organizationId, permission, siteId))) redirect(path(organizationId, "forbidden")); }
async function finish(organizationId: string, status: string) { revalidatePath(`/org/${organizationId}/governance`); redirect(path(organizationId, status)); }

async function insert(formData: FormData, schema: any, table: string, permission: PermissionCode, map: (data: any) => any = (data) => data) { const organizationId = organization(formData); const parsed = schema.safeParse(values(formData)); if (!parsed.success) return finish(organizationId, "invalid"); await guard(organizationId, permission, parsed.data.site_id); const { error } = await (await client()).from(table).insert({ organization_id: organizationId, ...map(parsed.data) }); await finish(organizationId, error ? "error" : "saved"); }

export async function createCommittee(formData: FormData) { return insert(formData, committeeSchema, "committees", "committees.manage"); }
export async function createPeriod(formData: FormData) { return insert(formData, periodSchema, "committee_periods", "committees.manage"); }
export async function addCommitteeMember(formData: FormData) { return insert(formData, committeeMemberSchema, "committee_members", "committees.manage"); }
export async function createMeeting(formData: FormData) { return insert(formData, meetingSchema, "committee_meetings", "committees.manage", (data) => ({ ...data, scheduled_at: iso(data.scheduled_at) })); }
export async function addAgendaItem(formData: FormData) { return insert(formData, agendaSchema, "meeting_agenda_items", "committees.manage"); }
export async function recordAttendance(formData: FormData) { return insert(formData, attendanceSchema, "meeting_attendance", "committees.manage"); }
export async function createMinutes(formData: FormData) { const organizationId = organization(formData); const parsed = minutesSchema.safeParse(values(formData)); if (!parsed.success) return finish(organizationId, "invalid"); await guard(organizationId, "committees.manage"); const { error } = await (await client()).from("meeting_minutes").upsert({ organization_id: organizationId, committee_meeting_id: parsed.data.committee_meeting_id, content: { body: parsed.data.content } }, { onConflict: "committee_meeting_id" }); await finish(organizationId, error ? "error" : "saved"); }
export async function createCommitteeCommitment(formData: FormData) { return insert(formData, commitmentSchema, "committee_commitments", "committees.manage", (data) => ({ ...data, due_at: iso(data.due_at) })); }
export async function updateMinutesStatus(formData: FormData) { const organizationId = organization(formData); const parsed = statusSchema.safeParse(values(formData)); if (!parsed.success) return finish(organizationId, "invalid"); await guard(organizationId, parsed.data.status === "approved" ? "committees.approve" : "committees.manage"); const { error } = await (await client()).from("meeting_minutes").update({ status: parsed.data.status }).eq("organization_id", organizationId).eq("id", parsed.data.id); await finish(organizationId, error ? "transition-error" : "saved"); }
export async function signMinutes(formData: FormData) { const organizationId = organization(formData); const minuteId = uuid.safeParse(formData.get("meeting_minutes_id")); const role = z.string().trim().min(2).max(80).safeParse(formData.get("signer_role")); if (!minuteId.success || !role.success) return finish(organizationId, "invalid"); await guard(organizationId, "committees.read"); const { userId } = await requireAuthenticatedUser(); const db = await client(); const { data: minutes } = await db.from("meeting_minutes").select("content").eq("organization_id", organizationId).eq("id", minuteId.data).maybeSingle(); if (!minutes) return finish(organizationId, "notfound"); const content = JSON.stringify(minutes.content); const { error } = await db.from("meeting_minute_signatures").insert({ organization_id: organizationId, meeting_minutes_id: minuteId.data, signer_user_id: userId, signer_role: role.data, content_hash: createHash("sha256").update(content).digest("hex"), content_snapshot: minutes.content }); await finish(organizationId, error ? "signature-error" : "signed"); }

export async function createAuditProgram(formData: FormData) { return insert(formData, auditProgramSchema, "audit_programs", "audits.manage", (data) => ({ ...data, criteria: data.criteria ? [data.criteria] : [] })); }
export async function createAuditEngagement(formData: FormData) { return insert(formData, auditEngagementSchema, "audit_engagements", "audits.manage", (data) => ({ ...data, criteria: data.criteria ? [data.criteria] : [], scheduled_at: iso(data.scheduled_at) })); }
export async function addAuditTeamMember(formData: FormData) { return insert(formData, auditTeamSchema, "audit_team_members", "audits.manage", (data) => ({ audit_engagement_id: data.audit_engagement_id, organization_member_id: data.organization_member_id, team_role: data.team_role, independence_declared_at: data.independence_declared ? new Date().toISOString() : null })); }
export async function addAuditAgendaItem(formData: FormData) { return insert(formData, auditAgendaSchema, "audit_agenda_items", "audits.manage", (data) => ({ ...data, scheduled_at: iso(data.scheduled_at) })); }
export async function addAuditChecklist(formData: FormData) { return insert(formData, auditChecklistSchema, "audit_checklists", "audits.manage"); }
export async function attachAuditEvidence(formData: FormData) { return insert(formData, auditEvidenceSchema, "audit_evidences", "audits.manage"); }
export async function createAuditFinding(formData: FormData) { return insert(formData, auditFindingSchema, "audit_findings", "audits.manage"); }
export async function createAuditAction(formData: FormData) { return insert(formData, auditActionSchema, "audit_actions", "audits.manage", (data) => ({ ...data, due_at: iso(data.due_at) })); }
export async function createAuditReport(formData: FormData) { return insert(formData, auditReportSchema, "audit_reports", "audits.manage"); }
export async function updateAuditStatus(formData: FormData) { const organizationId = organization(formData); const parsed = statusSchema.safeParse(values(formData)); const table = z.enum(["audit_engagements", "audit_findings", "audit_actions", "audit_reports"]).safeParse(formData.get("table")); if (!parsed.success || !table.success) return finish(organizationId, "invalid"); const requiresApproval = ["approved", "verified", "closed"].includes(parsed.data.status); await guard(organizationId, requiresApproval ? "audits.approve" : "audits.manage"); const { error } = await (await client()).from(table.data).update({ status: parsed.data.status }).eq("organization_id", organizationId).eq("id", parsed.data.id); await finish(organizationId, error ? "transition-error" : "saved"); }
export async function attachAuditActionEvidence(formData: FormData) { const organizationId = organization(formData); const actionId = uuid.safeParse(formData.get("audit_action_id")); const versionId = uuid.safeParse(formData.get("document_version_id")); if (!actionId.success || !versionId.success) return finish(organizationId, "invalid"); await guard(organizationId, "audits.manage"); const { error } = await (await client()).from("audit_actions").update({ evidence_document_version_id: versionId.data }).eq("organization_id", organizationId).eq("id", actionId.data); await finish(organizationId, error ? "evidence-error" : "evidence-saved"); }

export async function createManagementReview(formData: FormData) { return insert(formData, managementReviewSchema, "management_reviews", "audits.manage", (data) => ({ ...data, minutes_content: { body: data.minutes_content } })); }
export async function addManagementEntry(formData: FormData) { return insert(formData, managementEntrySchema, "management_review_entries", "audits.manage", (data) => ({ management_review_id: data.management_review_id, entry_type: data.entry_type, content: { body: data.content } })); }
export async function addManagementDecision(formData: FormData) { return insert(formData, managementDecisionSchema, "management_review_decisions", "audits.manage"); }
export async function createManagementCommitment(formData: FormData) { return insert(formData, managementCommitmentSchema, "management_review_commitments", "audits.manage", (data) => ({ ...data, due_at: iso(data.due_at) })); }
export async function updateManagementReviewStatus(formData: FormData) { const organizationId = organization(formData); const parsed = statusSchema.safeParse(values(formData)); if (!parsed.success) return finish(organizationId, "invalid"); await guard(organizationId, parsed.data.status === "approved" ? "audits.approve" : "audits.manage"); const { error } = await (await client()).from("management_reviews").update({ status: parsed.data.status }).eq("organization_id", organizationId).eq("id", parsed.data.id); await finish(organizationId, error ? "transition-error" : "saved"); }
